### ISSUE TITLE
BUG统一提交地址， 立马解决，世界上最勤快的开源

### ISSUE THREAD

**Issue by DotNetNext** [DotNetNext/SqlSugar#1077]
https://www.donet5.com/Ask 统一提交入口

**Comment by isharrrry** [comment]
在基于使用.net standard 2.0项目对实体类建模，目的是为了兼容net framework/net core。在对实体类建模时，类似于SugarColumn这样的字段注解，要求具有SqlSugar依赖，因此必须选择使用.net standard 2.1或者.net framework。这对兼容net framework/net core的实体建模项目很不友好，后续是否考虑将字段注解作为.net standard 2.0子项目发布，或者兼容EF core的字段注解？
