### ISSUE TITLE
db.Ado.SqlQueryAsync会偶发报错

### ISSUE THREAD

**Issue by tanyo520** [DotNetNext/SqlSugar#1119]
调用 db.Ado.SqlQueryAsync会偶发报如下错误：
There is already an open DataReader associated with this Connection which must be closed first.
这个是啥问题导致

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/212026283-676930f1-e3ed-42d5-a509-b04ee3430162.png)

**Comment by tanyo520** [comment]
> 这个线程安全问题 有没有少await

感谢 昨天找到官网的faq文档了

**Comment by DotNetNext** [comment]
那我就先关闭了，有问题发新的issue
