### ISSUE TITLE
Aop的事件中注入Scope类型对象，获的值不一致

### ISSUE THREAD

**Issue by MicroHeartWangZheng** [DotNetNext/SqlSugar#1121]
下面是注入多个SqlSugarScope
```var connectionStrings = configuration.GetSection("connectionStrings").GetChildren();
            foreach (var connectionString in connectionStrings)
            {
                var sqlSuagrConnectionConfig = new ConnectionConfig
                {
                    DbType = DbType.MySql,
                    ConnectionString = connectionString.Value,
                    ConfigId = connectionString.Key,
                    IsAutoCloseConnection = true,
                };

                services.AddSingleton<ISqlSugarClient>(seviceProvider =>
                {
                    sqlSuagrConnectionConfig.AopEvents = new AopEvents()
                    {
                        OnLogExecuted = (sql, paras) =>
                        {
                           //我想在记录日志时，传递一个参数EventId
                            var eventIdProvider = seviceProvider.GetService<EventIdProvider>();
                            var logger = seviceProvider.GetService<ILogger<SqlSugarClient>>();
                            logger.LogInformation($"{eventIdProvider.EventId}   sql:{sql} paras:{JsonConvert.SerializeObject(paras)}");
                        }
                    };
                    return new SqlSugarScope(sqlSuagrConnectionConfig);
                });
            }
```

下面是EventIdProvider的实现
```   
public class EventIdProvider
    {
        public EventId EventId { get; set; }

        public EventIdProvider()
        {
            string name = DateTime.Now.ToString("yyyyMMddHHmmssfffff") ?? "";
            EventId = new EventId(0, name);
        }
    }
```

//EventIdProvider 的注入 是Scope类型的
 
``` services.AddScoped<EventIdProvider>(); ```

//加了一个Action过滤器 ，问题就在 同一个请求中  过滤器中的EventId值和Aop中的EventId不一致  
```
public class ActionLogFilter : IActionFilter
    {
        private readonly ILogger<ActionLogFilter> logger;

        private readonly EventIdProvider eventIdProvider;

        private readonly ICurrentUserService currentUserService;

        public ActionLogFilter(ILogger<ActionLogFilter> logger, EventIdProvider eventIdProvider, ICurrentUserService currentUserService)
        {
            this.logger = logger;
            this.eventIdProvider = eventIdProvider;
            this.currentUserService = currentUserService;
        }

        public void OnActionExecuted(ActionExecutedContext context)
        {
            if (context.Exception != null || context.Result is Microsoft.AspNetCore.Mvc.FileStreamResult)
                return;
            logger.LogDebug(eventIdProvider.EventId, $"请求返回：{JsonConvert.SerializeObject(context.Result)}");
        }

        public void OnActionExecuting(ActionExecutingContext context)
        {
            logger.LogDebug(eventIdProvider.EventId, $"操作人Id:{currentUserService?.User?.Id} \r\n" +
                                                     $"操作人：{currentUserService?.User?.Name}  \r\n" +
                                                     $"请求地址：{context.HttpContext.Request.Path} \r\n" +
                                                     $"请求方式：{context.HttpContext.Request.Method} \r\n" +
                                                     $"请求参数：{JsonConvert.SerializeObject(context.ActionArguments.Values)}");
        }
    }
```

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/212250379-986eed2c-f0d1-4ed1-baca-8b3d00af8b1f.png)
AOPyid应该是在我圈的地方加

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/212250692-a4acd75d-3f58-4fa8-ac83-adccedffc5e3.png)

**Comment by MicroHeartWangZheng** [comment]
修改后的注入方式 ，同一请求中，执行SQL的EventId 和 过滤器中的EventId 还是不一样。   前者数值固定不变


`            var seviceProvider = services.BuildServiceProvider();
            #region 注入SqlSugar
            var connectionStrings = configuration.GetSection("connectionStrings").GetChildren();
            foreach (var connectionString in connectionStrings)
            {
                var sqlSugarScope = new SqlSugarScope(new ConnectionConfig()
                {
                    DbType = DbType.MySql,
                    ConnectionString = connectionString.Value,
                    ConfigId = connectionString.Key,
                    IsAutoCloseConnection = true,
                }, 
                db =>db.Aop.OnLogExecuted = (sql, paras) =>
                    {
                        var eventIdProvider = seviceProvider.GetService<EventIdProvider>();
                        var logger = seviceProvider.GetService<ILogger<SqlSugarScope>>();
                        logger.LogInformation($"{eventIdProvider.EventId}   sql:{sql} paras:{JsonConvert.SerializeObject(paras)}");
                    });
                services.AddSingleton<ISqlSugarClient>(sqlSugarScope);
            }
            #endregion`

**Comment by MicroHeartWangZheng** [comment]
修改后的注入方式 ，同一请求中，执行SQL的EventId 和 过滤器中的EventId 还是不一样。   前者数值固定不变


`            var seviceProvider = services.BuildServiceProvider();
            #region 注入SqlSugar
            var connectionStrings = configuration.GetSection("connectionStrings").GetChildren();
            foreach (var connectionString in connectionStrings)
            {
                var sqlSugarScope = new SqlSugarScope(new ConnectionConfig()
                {
                    DbType = DbType.MySql,
                    ConnectionString = connectionString.Value,
                    ConfigId = connectionString.Key,
                    IsAutoCloseConnection = true,
                }, 
                db =>db.Aop.OnLogExecuted = (sql, paras) =>
                    {
                        var eventIdProvider = seviceProvider.GetService<EventIdProvider>();
                        var logger = seviceProvider.GetService<ILogger<SqlSugarScope>>();
                        logger.LogInformation($"{eventIdProvider.EventId}   sql:{sql} paras:{JsonConvert.SerializeObject(paras)}");
                    });
                services.AddSingleton<ISqlSugarClient>(sqlSugarScope);
            }
            #endregion`

**Comment by MicroHeartWangZheng** [comment]
![image](https://user-images.githubusercontent.com/14367051/212586197-05f99970-79c7-475f-9d0b-77836167bf99.png)

**Comment by MicroHeartWangZheng** [comment]
![image](https://user-images.githubusercontent.com/14367051/212586197-05f99970-79c7-475f-9d0b-77836167bf99.png)

**Comment by MicroHeartWangZheng** [comment]
![image](https://user-images.githubusercontent.com/14367051/212586704-54db8ed6-d0cf-4021-ba3c-6067a8d74f88.png)

**Comment by MicroHeartWangZheng** [comment]
`                services.AddScoped<ISqlSugarClient>(serviceProvider => new SqlSugarClient(new ConnectionConfig()
                {
                    DbType = DbType.MySql,
                    ConnectionString = connectionString.Value,
                    ConfigId = connectionString.Key,
                    IsAutoCloseConnection = true,
                },
               db => db.Aop.OnLogExecuted = (sql, paras) =>
               {
                   var eventIdProvider = serviceProvider.GetService<EventIdProvider>();
                   var logger = serviceProvider.GetService<ILogger<SqlSugarClient>>();
                   logger.LogInformation($"{eventIdProvider.EventId}   sql:{sql} paras:{JsonConvert.SerializeObject(paras)}");
               }));`

换成了  SqlSugarClient 也是一样

**Comment by MicroHeartWangZheng** [comment]
> ![image](https://user-images.githubusercontent.com/12455385/212250379-986eed2c-f0d1-4ed1-baca-8b3d00af8b1f.png) AOP应该是在我圈的地方加

修改后的注入方式 ，同一请求中，执行SQL的EventId 和 过滤器中的EventId 还是不一样。   前者数值固定不变
          

           `var seviceProvider = services.BuildServiceProvider();
            var connectionStrings = configuration.GetSection("connectionStrings").GetChildren();
            foreach (var connectionString in connectionStrings)
            {
                var sqlSugarScope = new SqlSugarScope(new ConnectionConfig()
                {
                    DbType = DbType.MySql,
                    ConnectionString = connectionString.Value,
                    ConfigId = connectionString.Key,
                    IsAutoCloseConnection = true,
                }, 
                db =>db.Aop.OnLogExecuted = (sql, paras) =>
                    {
                        var eventIdProvider = seviceProvider.GetService<EventIdProvider>();
                        var logger = seviceProvider.GetService<ILogger<SqlSugarScope>>();
                       //这里生成的EventId值 固定不变
                        logger.LogInformation($"{eventIdProvider.EventId}   sql:{sql} paras:{JsonConvert.SerializeObject(paras)}");
                    });
                services.AddSingleton<ISqlSugarClient>(sqlSugarScope);
            }`

**Comment by DotNetNext** [comment]
多租户AOP需要 foreach 一下

db.GetConnection(i).Aop.OnLogExecuted

如果用的ConnectionScope需要换成 
db.GetConnectionScope (i).Aop.OnLogExecuted

**Comment by DotNetNext** [comment]
还有疑问吗

**Comment by DotNetNext** [comment]
长期未回复，有疑问发新的issue
