### ISSUE TITLE
列 unique 怎么做?

### ISSUE THREAD

**Issue by mjz17** [DotNetNext/SqlSugar#1125]
你好 列不许重复 unique 怎么做?

**Comment by DotNetNext** [comment]
CodeFirst可以设置唯一索引
![image](https://user-images.githubusercontent.com/12455385/214229381-804a0e71-e786-45f2-9f8c-191183d27351.png)

**Comment by DotNetNext** [comment]
还有疑问吗？

**Comment by DotNetNext** [comment]
还有疑问发新的ISSUE
