### ISSUE TITLE
使用SqlSugarScope，因为注入禁用了委托参数，获取不到指定服务

### ISSUE THREAD

**Issue by MicroHeartWangZheng** [DotNetNext/SqlSugar#1126]
````#region SqlSugarClient 使用 没问题
//foreach (var connectionString in connectionStrings)
//{
//    builder.Services.AddScoped<ISqlSugarClient>(serviceProvider => new SqlSugarClient(new ConnectionConfig()
//    {
//        DbType = DbType.MySql,
//        ConnectionString = connectionString,
//        IsAutoCloseConnection = true,
//        ConfigId = connectionString.Contains("Model") ? "Model" : "Basic"
//    },
//    db => db.Aop.OnLogExecuted = (sql, paras) =>
//    {
//        var logger = serviceProvider.GetService<ILogger<SqlSugarClient>>();
//        var eventIdProvider = serviceProvider.GetService<EventIdProvider>();
//        logger.LogInformation($"执行了SQL：EventId:{eventIdProvider.EventId} \r\n sql:{sql} paras:{JsonConvert.SerializeObject(paras)}");
//    }));
//} 
#endregion````


但是使用了  SqlSugarScope，因为注入禁用了委托参数，获取不到指定服务。想要获取Scope类型的服务，导致只能在外面获取，这就导致Scope类型的服务一直是同一个。

````#region SqlSugarScope，每次请求 执行SQL语句中的EventId值固定不变

var serviceProvider = builder.Services.BuildServiceProvider(); 
 
foreach (var connectionString in connectionStrings)
{
    builder.Services.AddSingleton<ISqlSugarClient>(new SqlSugarScope(new ConnectionConfig()
    {
        DbType = DbType.MySql,
        ConnectionString = connectionString,
        IsAutoCloseConnection = true,
        ConfigId = connectionString.Contains("Model") ? "Model" : "Basic"
    },
    db => db.Aop.OnLogExecuted = (sql, paras) =>
    {
        var logger = serviceProvider.GetService<ILogger<SqlSugarScope>>();
        var eventIdProvider = serviceProvider.GetService<EventIdProvider>();
        //eventIdProvider.EventId 值固定不变， 因为SqlSugarScope不能传委托参数serviceProvider
        logger.LogInformation($"{eventIdProvider.EventId}  sql:{sql} paras:{JsonConvert.SerializeObject(paras)}");
    }));
} 
#endregion````

完整代码示例在 [https://github.com/MicroHeartWangZheng/SS](url)

**Comment by DotNetNext** [comment]
提供完整的GITHUB代码

**Comment by DotNetNext** [comment]
上面的地址无效

**Comment by MicroHeartWangZheng** [comment]
> 上面的地址无效

https://github.com/MicroHeartWangZheng/SS

**Comment by DotNetNext** [comment]
还是无效地址

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/215317081-3c44456e-e2c4-41d4-9c4e-7a3d3daa181d.png)

**Comment by MicroHeartWangZheng** [comment]
不好意思，设置成私有仓库了，已经改了。还是刚才那个网址

**Comment by MicroHeartWangZheng** [comment]
> 还是无效地址

不好意思，设置成私有仓库了，已经改了。还是刚才那个网址

**Comment by DotNetNext** [comment]
public UserController(ILogger<UserController> logger, **ISqlSugarClient  sqlSugarClients**, EventIdProvider eventIdProvider)

**Comment by DotNetNext** [comment]
应该改成这样

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/215459744-e2d1ebec-0403-48fe-9642-9b45baf72e32.png)

**Comment by MicroHeartWangZheng** [comment]
![image](https://user-images.githubusercontent.com/14367051/215466299-943f6423-edc8-419d-a6b6-55d3ec1a664f.png)
![image](https://user-images.githubusercontent.com/14367051/215466412-024baee9-2469-4767-a580-6cfe37c8a41a.png)
我按照图片上修改的  报错了，我调试看了 初始化配置的时候，ConfigId 是“Model”  
 

但是 this.basicClient = sqlSugarClients.AsTenant().GetConnection("Basic");  这个不报错， 我注释上面的。
![image](https://user-images.githubusercontent.com/14367051/215469120-a228626b-aeb7-4015-a844-52f613fcda2a.png)
按道理说 EventIdProvider注入类型是Scope，应该同一个请求参生的 值一样。 是我哪里搞错了吗？

**Comment by MicroHeartWangZheng** [comment]
> ![image](https://user-images.githubusercontent.com/12455385/215459744-e2d1ebec-0403-48fe-9642-9b45baf72e32.png)

我这个有两个数据库链接 ，其实不是租户，就是普通的连接两个数据库。

**Comment by MicroHeartWangZheng** [comment]
> 应该改成这样

我更新了代码，您可以看看。

**Comment by MicroHeartWangZheng** [comment]
User表

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for User
-- ----------------------------
DROP TABLE IF EXISTS `User`;
CREATE TABLE `User`  (
  `Id` int NOT NULL,
  `Name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`Id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

**Comment by MicroHeartWangZheng** [comment]
IkWord表


SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for IkWord
-- ----------------------------
DROP TABLE IF EXISTS `IkWord`;
CREATE TABLE `IkWord`  (
  `Id` int NOT NULL AUTO_INCREMENT,
  `Word` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `Type` int NOT NULL,
  PRIMARY KEY (`Id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 12 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = COMPACT;

SET FOREIGN_KEY_CHECKS = 1;

**Comment by DotNetNext** [comment]
换成租户注入

**Comment by DotNetNext** [comment]
var db = new SqlSugarScope(new List<ConnectionConfig>()
{
 new ConnectionConfig(){ConfigId="A",DbType=DbType.SqlServer,ConnectionString=..,IsAutoCloseConnection=true},
 new ConnectionConfig(){ConfigId="B",DbType=DbType.MySql,ConnectionString=..,IsAutoCloseConnection=true  },
 new ConnectionConfig(){ConfigId="C",DbType=DbType.MySql,ConnectionString=..,IsAutoCloseConnection=true  }
});
注入这个对象

**Comment by MicroHeartWangZheng** [comment]
> var db = new SqlSugarScope(new List() { new ConnectionConfig(){ConfigId="A",DbType=DbType.SqlServer,ConnectionString=..,IsAutoCloseConnection=true}, new ConnectionConfig(){ConfigId="B",DbType=DbType.MySql,ConnectionString=..,IsAutoCloseConnection=true }, new ConnectionConfig(){ConfigId="C",DbType=DbType.MySql,ConnectionString=..,IsAutoCloseConnection=true } }, db=>{ db.GetConnection("A").Aop.xxx=xxx db.GetConnection("B").Aop.xxx=xxx }); 注入这个对象

如果用SqlSugarClient，就没有其他的办法了吗？

**Comment by DotNetNext** [comment]
一样用法， 就是一个对象扔多个connection，然后用租户 取拿子DB

**Comment by DotNetNext** [comment]
SqlSugarScope和SqlSugarClient都可以， IOC用 ISqlSugarClient
只不过SqlSugarScope是单例 
SqlSugarClient 是Scoped注入 他们注入方式不同

**Comment by DotNetNext** [comment]
https://www.donet5.com/Home/Doc?typeId=2246   这个是文档推荐这样实现

你那种写法也可以需要改成，不过这样就麻烦了
.AddSingleton<List<ISqlSugarClient>>(List<ISqlSugarClient>)

**Comment by DotNetNext** [comment]
还有疑问发新的issue这个先关闭了

**Comment by MicroHeartWangZheng** [comment]
> ![image](https://user-images.githubusercontent.com/14367051/215466299-943f6423-edc8-419d-a6b6-55d3ec1a664f.png) ![image](https://user-images.githubusercontent.com/14367051/215466412-024baee9-2469-4767-a580-6cfe37c8a41a.png) 我按照图片上修改的 报错了，我调试看了 初始化配置的时候，ConfigId 是“Model”
> 
> 但是 this.basicClient = sqlSugarClients.AsTenant().GetConnection("Basic"); 这个不报错， 我注释上面的。 ![image](https://user-images.githubusercontent.com/14367051/215469120-a228626b-aeb7-4015-a844-52f613fcda2a.png) 按道理说 EventIdProvider注入类型是Scope，应该同一个请求参生的 值一样。 是我哪里搞错了吗？

感觉作者是为了赶紧关闭issues而回答，提的两个问题一个都没解决 ，作者根本就没有用心解决问题。这个框架用了一段时间，真的觉得封装的越来越乱，好像是为了兼容各种功能，没有做好提前规划，而且部分api真的反人类用法。  确实ORM功能很多，很全，按照文档也能实现，但是有些写法真的反人类。 特别想吐槽 多表联查的 SelectAll() ，还有 SqlSugarScope的注入 不能使用委托参数，我是真的不理解。我水平有限，但是这种反人类api，只能去死记硬背，跟微软的的设计格格不入。
