### ISSUE TITLE
SqlSugarScope的Aop在QuartzJob內失效

### ISSUE THREAD

**Issue by Yumitoya8569** [DotNetNext/SqlSugar#1128]
## 環境
.Net 7
Oracle 11g
SqlSugarCore 5.1.3.51

## 問題
DbFactory類別為單例注入並使用UseDB取得連線(實際情況會切換連線, 這裡簡化)
分別測試過(A)、(B)、(C)、(D) 4種設定方式
在Quartz的Job內使用查詢均無進入OnLogExecuting
補充: 這是WebApi專案, Quartz在初始化後跑在背景執行續
```
public class DbFactory
{
        private static SqlSugarScope _db =  new SqlSugarScope(new ConnectionConfig()
        {
            ConfigId = "System",
            DbType = SqlSugar.DbType.Oracle,
            ConnectionString = "MyConnectionString...",
            IsAutoCloseConnection = true
        }, d => {
            // (A)
            d.Aop.OnLogExecuting =  (sql, p) =>
            {
                System.Diagnostics.Debug.WriteLine("{0}", sql);
            };

            // (B)
            d.GetConnection("System").Aop.OnLogExecuting =  (sql, p) =>
            {
                System.Diagnostics.Debug.WriteLine("{0}", sql);
            };

            // (C)
            d.GetConnectionScope("System").Aop.OnLogExecuting =  (sql, p) =>
            {
                System.Diagnostics.Debug.WriteLine("{0}", sql);
            };
        });
       
        public DbFactory()
        {
        }

        public SqlSugarScopeProvider UseDB()
        {
            var connScope = _db.GetConnectionScope("System");

            // (D)
            connScope.Aop.OnLogExecuting =  (sql, p) =>
            {
                System.Diagnostics.Debug.WriteLine("{0}", sql);
            };

            return connScope;
        }       
}
```

**Comment by DotNetNext** [comment]
db.GetConnectionScope AOP也要用 db.GetConnectionScope("xx").Aop  ，2边要一致

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/220295441-ceb48899-e903-41b4-9f26-684ad9180b33.png)

**Comment by DotNetNext** [comment]
你这个情况需提供完整的DEMO，并且我这边能重现的。

**Comment by DotNetNext** [comment]
C应该是对象的，其他都是错的

**Comment by DotNetNext** [comment]
你可以打个断点看一下，是不是断点有没有进来

**Comment by Yumitoya8569** [comment]
稍微補充一下:
1. 實際上在ApiController的HttpGet方法調用, 以上設置都能生效
    我知道(C)是建議的, 順便建議調整一下文檔2.1的範例代碼https://www.donet5.com/home/Doc?typeId=1181
   ```//db.GetConnection(i).Aop```

2. 斷點有測試過, configAction有執行, 但如果斷在OnLogExecuting內永遠不會執行

3. 後續會補上能重現的DEMO

**Comment by DotNetNext** [comment]
这边可以重现了，晚点修复，因为兼容了 Q队列的线程安全，导致AOP失效

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/220335523-6d174be0-4085-4fa4-a1cd-e3704dfd1f17.png)

这样写就可以了，因为初始的线程和 执行队列的线程不是一个方法

**Comment by DotNetNext** [comment]
把GetConnection在方法内获取就能到AOP了

**Comment by DotNetNext** [comment]
不要在构造函数，因为构造函数是静态的

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/220336065-b6e38219-ec57-45ba-8475-7ade62fbc491.png)

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/220336140-dfacf0b7-274f-4a66-9491-a86c1ad5cb75.png)

**Comment by DotNetNext** [comment]
如果还有疑问，我把我的DEMO给你，我这边按我这么写可以执行

**Comment by Yumitoya8569** [comment]
謝謝, 我有機會會測試一下

另外我想了解一下這個問題是基於muti-thread觸發嗎?
內部原理是什麼?
因為運用面上很難避免構造函數, 想了解一下原理看有沒有機會繞過

**Comment by DotNetNext** [comment]
那就先关闭了，还有问题在新开一个isssue
