### ISSUE TITLE
是否支持限制更新数目

### ISSUE THREAD

**Issue by jinzaz** [DotNetNext/SqlSugar#1132]
例如更新符合条件的固定3条记录，是否支持

**Comment by DotNetNext** [comment]
var list=db.Queryable<Order>().Take(3).ToList();
            db.Updateable(list).ExecuteCommand();

**Comment by DotNetNext** [comment]
目前可以查询在删除

**Comment by jinzaz** [comment]
好的，这种方式对我可能不合适，这种会导致并发时重复查询到前三条再修改，谢谢回复
