### ISSUE TITLE
使用PG数据库是修改字段长度超过4000 异常

### ISSUE THREAD

**Issue by Sunyao-work** [DotNetNext/SqlSugar#1133]
当使用pg数据库时，修改字段长度超过4000 更新脚本将会将varchar(length) 变成varchar(max)。但是pg不支持varchar(max)

**Comment by DotNetNext** [comment]
5.1.3.44-preview06  推荐

[SugarColumn(ColumnDataType = StaticConfig.CodeFirst_BigString)]

**Comment by DotNetNext** [comment]
建表用这个

**Comment by DotNetNext** [comment]
pgsql是没有varchar max的

**Comment by DotNetNext** [comment]
还有疑问发新的issues
