### ISSUE TITLE
子查询-字符串拼接SelectStringJoin不支持达梦数据库

### ISSUE THREAD

**Issue by leehomlee** [DotNetNext/SqlSugar#1136]
如题，
![image](https://user-images.githubusercontent.com/11976286/225188576-12da9d82-725f-4dd4-a1f5-17e122d44cea.png)
默认生成了STRING_AGG

**Comment by DotNetNext** [comment]
好的，我今天支持一下

**Comment by DotNetNext** [comment]
源码已修复，后面版本发布到NUGET
