### ISSUE TITLE
bug: 单表查询映射到实体，字段均为null

### ISSUE THREAD

**Issue by langhaoabcd** [DotNetNext/SqlSugar#1137]
从v4 升级到了 v5,出现了以下问题，新开的项目下测试结果
1.正常情况： 查询后直接取first
![image](https://user-images.githubusercontent.com/39892654/225509663-e91283a2-2878-43fd-aea0-5f73bfd0c082.png)
能查到结果
![image](https://user-images.githubusercontent.com/39892654/225509823-5d63db5f-ab7c-4d40-9a75-f85e7f25d919.png)
![image](https://user-images.githubusercontent.com/39892654/225509875-640c718a-ed21-4bef-a0a7-a6a04567659a.png)

2.异常情况： 查询到取结果中间加了段代码
![image](https://user-images.githubusercontent.com/39892654/225510100-de048821-5441-400a-a4d0-f8dafafd9ac2.png)
结果为null
![image](https://user-images.githubusercontent.com/39892654/225510201-fe2d8df6-4ef2-4692-9159-e5c4a61131af.png)
生成两段sql
![image](https://user-images.githubusercontent.com/39892654/225510237-a578ce81-76dc-47af-9663-34112d44606f.png)

**Comment by langhaoabcd** [comment]
感觉这是个挺严重的问题

**Comment by DotNetNext** [comment]
你实体没有get set吧 或者用了Private

**Comment by DotNetNext** [comment]
一般出现这个问题都是实体问题

**Comment by langhaoabcd** [comment]
实体只加了一个属性
![image](https://user-images.githubusercontent.com/39892654/225520358-adda809f-4f6f-47d9-b2f6-695e0b589808.png)

符合配置实体的规范
对于 CRUD来说只需要配置主键和自增列就行了 ，如果类的名称和数据库不一样可以设置数据库中的名称

**Comment by langhaoabcd** [comment]
我开始也以为是实体的问题，百思不得其解。最后发现是代码里这个判断的问题，不加就可以

**Comment by DotNetNext** [comment]
没听懂什么意思，如果还没有就名字不一样 需要suagrcolumns配置数据库名称

**Comment by DotNetNext** [comment]
看懂了，如果一个queryable多次使用 需要   queryable.Clone().Any()

**Comment by DotNetNext** [comment]
你的代码可以优化一下
var data=db.queryable<T>().xxx.First();
if(data==null) thow

**Comment by langhaoabcd** [comment]
好的
