### ISSUE TITLE
PostgreSql获取字段列表时排序问题

### ISSUE THREAD

**Issue by nexthero** [DotNetNext/SqlSugar#1138]
PostgreSql获取字段列表：DbMaintenance.GetColumnInfosByTableName()
返回结果能否按ordinal_position排序，或者把ordinal_position加到DbColumnInfo里

**Comment by DotNetNext** [comment]
默认就是按数据来排序的

**Comment by DotNetNext** [comment]
如果你查出来不是按数据库排序你可以提供一个建表语句给我

**Comment by nexthero** [comment]
CREATE TABLE "public"."bas_error_cause" (
  "id" varchar(40) COLLATE "pg_catalog"."default" NOT NULL,
  "error_cause_code" varchar(40) COLLATE "pg_catalog"."default" NOT NULL,
  "error_cause_name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "org_id" varchar(40) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "remark" varchar(400) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "create_id" varchar(40) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "create_time" timestamp(6) NOT NULL,
  "modify_id" varchar(40) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
  "modify_time" timestamp(6),
  "extras" text COLLATE "pg_catalog"."default",
  CONSTRAINT "bas_error_cause_pkey" PRIMARY KEY ("id")
);

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.61-preview01 预览版本已修复

**Comment by DotNetNext** [comment]
还有疑问发布新的ISSUES，先关闭
