### ISSUE TITLE
希望支持使用 NpgsqlDataSourceBuilder 创建 pgsql 的 Connection

### ISSUE THREAD

**Issue by ZeekoZhu** [DotNetNext/SqlSugar#1141]
根据[文档](https://www.npgsql.org/doc/types/enums_and_composites.html#mapping-your-clr-types) 目前使用的 TypeMapper 自定义类型方式已经被废弃了，需要通过 NpgsqlDataSourceBuilder 自定义数据库类型。

**Comment by DotNetNext** [comment]
db.Ado.Connection=你的Connection

**Comment by DotNetNext** [comment]
可以指定外部Connection

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/227709899-2e6351b2-9fbf-4313-92db-3d4436eea709.png)
我看可以全局配置

**Comment by ZeekoZhu** [comment]
> ![image](https://user-images.githubusercontent.com/12455385/227709899-2e6351b2-9fbf-4313-92db-3d4436eea709.png) 我看可以全局配置

![image](https://user-images.githubusercontent.com/13861843/227726735-930d53c3-788a-4450-9d76-cf61d0ad2873.png)

实际上这个也被标记废弃了。




> db.Ado.Connection=你的Connection

这样设置 Connection 时，只要保证 Connection 的生命周期跟 SugarClient 一致就行了吧？

**Comment by DotNetNext** [comment]
![image](https://user-images.githubusercontent.com/12455385/227754709-89453451-0970-45df-a18d-12ec9913badc.png)
那这个呢

**Comment by DotNetNext** [comment]
这样设置 Connection 时，只要保证 Connection 的生命周期跟 SugarClient 一致就行了吧？

是这样的，只在一个上下文就是同一个
