### ISSUE TITLE
NET 7.0 +SqlSugarCore 5.1.4.62 +sqlserver 2017 分页查询出的数据有重复项

### ISSUE THREAD

**Issue by zdw2018** [DotNetNext/SqlSugar#1143]
分页查询的代码是这个样子的：

![image](https://user-images.githubusercontent.com/36786472/228508142-567e90de-b7c0-4785-bdf2-aeb3df0d1283.png)

调试生成的 SQL语句如下：
![image](https://user-images.githubusercontent.com/36786472/228508187-382d980c-e69e-45df-9328-db567b7f393f.png)

后端代码拿到的数据:

![image](https://user-images.githubusercontent.com/36786472/228508224-4b18f1e1-a3fa-4a81-b586-41057c306b7f.png)

数据库中执行sql拿到的数据

![image](https://user-images.githubusercontent.com/36786472/228508261-138efd94-232f-445a-8034-d0f5f8d6ba7f.png)

这里执行的时候数据库执行sql和orm给到的数据不一致

在加载第二页的数据时候 ORM拿到的数据又包含第一页的数据
![image](https://user-images.githubusercontent.com/36786472/228508291-8e9eb1d7-b8b9-4180-bcd5-cefb5479680f.png)

![image](https://user-images.githubusercontent.com/36786472/228508311-78d1684e-1812-4cf9-a26a-d4d2696a2c52.png)

在在后端代码中拿到的 第一页数据和第一页数据中 存在相同的stock_id 项  40 、44 、46
视图中总共17条数据  这里面 存在三条重复数据 导致 有三条数据没法显示出来  ，如果pagesize设置为20则所有数据 都可以查询寻出来

**Comment by DotNetNext** [comment]
OrderBy 加上主键

**Comment by zdw2018** [comment]
为什么有的时候不加就不会出问题呢

**Comment by DotNetNext** [comment]
没有排序，如果不是Int主键可能会乱的

**Comment by DotNetNext** [comment]
分页最好加上排序

**Comment by DotNetNext** [comment]
如果还有疑问可以发新的贴子
