### ISSUE TITLE
为什么dbquery对象在未赋值的情况下会被修改

### ISSUE THREAD

**Issue by HZ-GeLiang** [DotNetNext/SqlSugar#1144]
我按照文档代码的 Scope模式：SqlSugarClient  模式, 进行了一个单表查询. 
然而我发现, query对象不能复用. 下面2个{} 中的代码是一模一样的

Nuget版本: 
 `  <PackageReference Include="sqlSugarCore" Version="5.1.4.63" />`

运行代码(源码粘贴上来显示有问题, 粘贴图片了)

![image](https://user-images.githubusercontent.com/16562680/229163273-9c9bf997-fbe6-4edd-96d8-ee776796b760.png)

然后控制器就输出了如下2个sql语句.

SELECT [Id],[UserName],[Birth] FROM [Students]  WHERE ( [Id] = @Id0 ) 
  
SELECT [Id],[UserName],[Birth] FROM [Students]  WHERE ( [Id] = @Id0 )  AND ( [Id] = @Id1 )   

根据认知,  query.Where(exp) 返回一个 queryable 对象,  上面代码中我没有把 query.where(exp)的 query对象重复赋值给 query, 那么理论上最后的输出的2个sql语句应该是一致的才对.

**Comment by DotNetNext** [comment]
queryable.Clone()，这样操作可以拷贝一个新对象 ，不然是引用类型，看文档queryable生命周期
