### ISSUE TITLE
SqlFunc.IIF生成的case when then else 语句 else 参数传null 传不了

### ISSUE THREAD

**Issue by dadazxy** [DotNetNext/SqlSugar#1145]
想要这样的语句
SELECT  "accountuuid" AS "accountuuid" , "authid" AS "postid" , 
COUNT(( CASE  WHEN ( "abnormaltype" =2 ) THEN 1  ELSE NULL END )) AS "listingabnormalcount" , 
FROM "t_test" GROUP BY "accountuuid","authid" 

生成的是

SELECT  "accountuuid" AS "accountuuid" , "authid" AS "postid" , 
COUNT(( CASE  WHEN ( "abnormaltype" = @Abnormaltype0 ) THEN "asin"  ELSE @MethodConst1 END )) AS "listingabnormalcount"  FROM "t_summaryabnormal" GROUP BY "accountuuid","authid"
@Abnormaltype0:2,@MethodConst1:

@MethodConst1传不了null

**Comment by DotNetNext** [comment]
SqlFunc.MappingColumn(default(string), "null")

可以通过MappingColumn非参数化处理

**Comment by DotNetNext** [comment]
//最新版本对不参数化进行了语法化  ，还有疑问发新的贴子

SqlFunc.MappingColumn<int>("null")
