### ISSUE TITLE
无实体建表进行分表

### ISSUE THREAD

**Issue by alinayaa** [DotNetNext/SqlSugar#1146]
希望增加**无实体建表进行分表**功能。
- 无实体建表会有一个**DateTime**字段
- 需要**指定此列**进行按照年、月、日、时进行分表
可在```SugarColumn```或```DynamicBuilder```中增加功能呢

**Comment by DotNetNext** [comment]
5.1.4.67-preview03  最新预览版本已经支持
     var type = db.DynamicBuilder().CreateClass("axx", new SugarTable()
                {
                     TableName= "azaDy_{year}{month}{day}"
                },null,null, new SplitTableAttribute(SplitType.Year))
                .CreateProperty("Id", typeof(long), new SugarColumn() { IsPrimaryKey = true })
                .CreateProperty("CreateTime", typeof(DateTime), new SugarColumn() { }, isSplitField:true)
                .WithCache()//缓存起来根据表名和字段名组合的KEY    
                .BuilderType();
   
                db.CodeFirst.InitTables(type);`

`

**Comment by DotNetNext** [comment]
长时间未回复，还有疑问请发新的issue
