### ISSUE TITLE
两表关联查询时，select子表信息未填充

### ISSUE THREAD

**Issue by sunlu** [DotNetNext/SqlSugar#1148]
query.Select((g, i) => new ReportGroupInfo()
            {
                Id =g.Id.SelectAll(),
                GroupInfo = i
            });

GroupInfo有时会填充完整数据，有时不填充，20%的偶发机率

经再次测试使用ToList()暂时没有发生此问题，使用ToListAsync()  会有一定机率出现

**Comment by DotNetNext** [comment]
是最新版本吗

**Comment by sunlu** [comment]
> 

是的

**Comment by DotNetNext** [comment]
我这边排查一下，周一前给你答复

**Comment by DotNetNext** [comment]
升级到预览版本  SqlSugarCore 5.1.4.67-preview13  测试一下，搜索时勾一下预览

**Comment by DotNetNext** [comment]
人还在不

**Comment by DotNetNext** [comment]
长期未回复，如果还有问题，发新isssue
