### ISSUE TITLE
建议 framework版本与 core 版本的nuge统一起来，否则多目标项目无法自动更新。

### ISSUE THREAD

**Issue by xxl-cc** [DotNetNext/SqlSugar#1155]
目前我是遇到了这种情况，我的项目是TargetFrameworks多目标项目，
需要分别引用sqlsugar与sqlsugarcore,但是，当存在更新的时候nuget无法自动正确的更新。需要手工替换项目里引用的版本号才可以。

**Comment by DotNetNext** [comment]
framework市场占有量越来越低，目前只有.net core的25% ，分开的目的是让用户打开源码方便，很多用户对于这种多架构的用不起来。长远角度看 framework将会消失。暂时不考虑你这种情况。
