### ISSUE TITLE
Postgresql -infinity 时间转换失败的问题

### ISSUE THREAD

**Issue by idea-zone** [DotNetNext/SqlSugar#1162]
报错误： System.InvalidCastException:“Can't read infinity value since Npgsql.DisableDateTimeInfinityConversions is enabled”

1.  设置    AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", false); 也无法解决这个问题
2.  在 ConnectionString 字符串添加  Convert Infinity DateTime=true 直接无法链接 

请问如何处理  Postgresql 中 timestamp without time zone 值为 -infinity 或者 infinity 的情况？

是否需要设置某些选项，或者可以设置自定义的类型转换的委托？

**Comment by DotNetNext** [comment]
这个默认是开启的，你是想关掉他吗 
AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", false); 目前是true sqlsugar中

**Comment by idea-zone** [comment]
> AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", false);

放到哪里，我不管是在 Program.Main 中设置，还是在 Startup 类里面设置，都会报错。

**Comment by DotNetNext** [comment]
StaticConfig.AppContext_ConvertInfinityDateTime = true;
 在程序启动时加上。
然后将代码更新到最新预览版本
SqlSugarCore 5.1.4.85-preview11

**Comment by idea-zone** [comment]
> StaticConfig.AppContext_ConvertInfinityDateTime = true; 在程序启动时加上。 然后将代码更新到最新预览版本 SqlSugarCore 5.1.4.85-preview11

感谢

**Comment by idea-zone** [comment]
再次感谢，已经解决了遇到的问题.
