### ISSUE TITLE
查詢時的映射沒有優先採用資料庫資料

### ISSUE THREAD

**Issue by Yumitoya8569** [DotNetNext/SqlSugar#1172]
## 環境
.Net 7
Oracle 11g
SqlSugarCore 5.1.4.89

## 情境
我們有以下實體:
```C#
  public class TableA
  {
      [SugarColumn(IsPrimaryKey = true)]
      public string id { get; set; } = string.Empty;

      public string name { get; set; } = string.Empty;

      public DateTime? create_utc { get; set; } = DateTime.UtcNow;
  }
```
相應的資料庫資料:
| id | name | create_utc |
| ---- | ---- | ---- | 
| a| aa | null |

我們使用查詢:
```C#
 _db.Queryable<TableA>().ToOffsetPageAsync(1, 20)
```
會得到結果:
| id | name | create_utc |
| ---- | ---- | ---- | 
| a| aa | 2023-07-11 14:26:26|

## 問題
我不確定這個情況是基於設計還是bug  
不過直覺上來講應該優先尊重資料庫的null值而非實體上的默認值

**Comment by DotNetNext** [comment]
目前设计是实体有值，并且你数据库没有值就不绑定了

**Comment by DotNetNext** [comment]
[SugarColumn(InsertServerTime =true, IsOnlyIgnoreUpdate =true)] 
  public DateTime CreateTime { get; set; }

 你看看改成这样能不能解决你插入默认值问题

**Comment by Yumitoya8569** [comment]
已把資料庫欄位改成not null來解決
不過這案例依然較超乎預期
建議再評估一下
謝謝

**Comment by DotNetNext** [comment]
已加入到计划，后面版本会支持到moressting配置
