### ISSUE TITLE
分表之后查询性能下降明显

### ISSUE THREAD

**Issue by aaa930811** [DotNetNext/SqlSugar#1175]
根据时间列分表之后，如果查询时间段的数据分散在2个及以上的表中的时候查询性能比单表查询慢很多，想问问是我查询方法不对吗？
···

 [MemoryDiagnoser, RankColumn]
    public class SqlSugarTestBenchmarker
    {
        private static string connstr = "Server=localhost;Port=3306;Database=SqlSugarTestDB;Uid=sa;Password=123456;Convert Zero Datetime=True;SslMode=none;AllowLoadLocalInfile=true;";

        DateTime starttime = Convert.ToDateTime("2023-07-15");
        DateTime endtime = Convert.ToDateTime("2023-08-15");

        public void GenerateData()
        {
            SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
            {
                ConnectionString = connstr,
                DbType = DbType.MySql,
                IsAutoCloseConnection = true
            }, db =>
            {
                db.Aop.OnLogExecuting = (sql, pars) =>
                {
                    Console.WriteLine(sql);//输出sql,查看执行sql 性能无影响
                };
            });
            var students = new List<Student>();
            var students2 = new List<StudentSplitTable>();
            for (int i = 0; i < 20000; i++)
            {
                int seed = i % 10;
                students.Add(new Student
                {
                    Id = Guid.NewGuid(),
                    Name = $"Test_{i}",
                    Sex = "男",
                    Phone = $"Phone_{i}",
                    CreateTime = DateTime.Now.AddMonths(seed),
                    IsDeleted = false
                });
                students2.Add(new StudentSplitTable
                {
                    Id = Guid.NewGuid(),
                    Name = $"Test_{i}",
                    Sex = "男",
                    Phone = $"Phone_{i}",
                    CreateTime = DateTime.Now.AddMonths(seed),
                    IsDeleted = false
                });
            }
            db.CodeFirst.InitTables<Student>();
            db.Fastest<Student>().BulkCopy(students);
            db.Fastest<StudentSplitTable>().SplitTable().BulkCopy(students2);
        }

        [Benchmark]
        public void StatisticBySingleTable()
        {
            int total = 0;
            SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
            {
                ConnectionString = connstr,
                DbType = DbType.MySql,
                IsAutoCloseConnection = true
            }, db =>
            {
                db.Aop.OnLogExecuting = (sql, pars) =>
                {
                    Console.WriteLine(sql);//输出sql,查看执行sql 性能无影响
                };
            });
            var list = db.Queryable<Student>().Where(x => x.CreateTime >= starttime && x.CreateTime < endtime).OrderByDescending(x => x.CreateTime).ToPageList(1, 1000);
        }

        [Benchmark]
        public void StatisticBySplitTable()
        {
            int total = 0;
            SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
            {
                ConnectionString = connstr,
                DbType = DbType.MySql,
                IsAutoCloseConnection = true
            }, db =>
            {
                db.Aop.OnLogExecuting = (sql, pars) =>
                {
                    Console.WriteLine(sql);//输出sql,查看执行sql 性能无影响
                };
            });
            var list = db.Queryable<StudentSplitTable>().SplitTable(starttime, endtime).OrderByDescending(x => x.CreateTime).ToPageList(1, 1000);
        }
    }

    public class Student
    {
        [SugarColumn(IsPrimaryKey = true, IndexGroupNameList = new string[] { "Id" })]
        public Guid Id { get; set; }

        [SugarColumn(IndexGroupNameList = new string[] { "Name" })]
        public string Name { get; set; }

        public string Sex { get; set; }

        [SugarColumn(IndexGroupNameList = new string[] { "Phone" })]
        public string Phone { get; set; }

        [SugarColumn(IndexGroupNameList = new string[] { "CreateTime" })]
        public DateTime CreateTime { get; set; }

        public bool IsDeleted { get; set; }
    }

    [SplitTable(SplitType.Month)]//按月分表 （自带分表支持 年、季、月、周、日）
    [SugarTable("StudentSplitTable_{year}{month}{day}")]//3个变量必须要有，这么设计为了兼容开始按年，后面改成按月、按日
    public class StudentSplitTable
    {
        [SugarColumn(IsPrimaryKey = true, IndexGroupNameList = new string[] { "Id" })]
        public Guid Id { get; set; }

        [SugarColumn(IndexGroupNameList = new string[] { "Name" })]
        public string Name { get; set; }

        public string Sex { get; set; }

        [SugarColumn(IndexGroupNameList = new string[] { "Phone" })]
        public string Phone { get; set; }

        [SplitField]
        [SugarColumn(IndexGroupNameList = new string[] { "CreateTime" })]
        public DateTime CreateTime { get; set; }

        public bool IsDeleted { get; set; }
    }
···
![image](https://github.com/DotNetNext/SqlSugar/assets/16344059/73765377-7ae5-4d68-8e53-03721e0ada7e)

**Comment by DotNetNext** [comment]
时间列加索引了吗

**Comment by DotNetNext** [comment]
跨月查询肯定是会慢些的

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/e25132e3-fb47-4d77-9b67-a229e12d7fb0)
你这个DEMO分页还是很快的

**Comment by DotNetNext** [comment]
比如你有1亿数据分了100个表，你查2个表肯定 查询一个表中有1亿数据的快

**Comment by DotNetNext** [comment]
你这种2万数据分表没什么意义

**Comment by aaa930811** [comment]
> 时间列加索引了吗

看上面的model，加过了的

**Comment by aaa930811** [comment]
> 你这种2万数据分表没什么意义

这只是一个测试，实际我的单表有3700W数据，性能下降更明显了

**Comment by aaa930811** [comment]
> 比如你有1亿数据分了100个表，你查2个表肯定 查询一个表中有1亿数据的快

但是我实际发现比查单表慢诶

**Comment by aaa930811** [comment]
> > 比如你有1亿数据分了100个表，你查2个表肯定 查询一个表中有1亿数据的快
> 
> 但是我实际发现比查单表慢诶

如果要查询的数据恰好只在其中的一个分表中那么确实是比单表查询快很多，但是实际情况几乎肯定会跨多个分表查询的

**Comment by DotNetNext** [comment]
那就要合适分表，比如按年

**Comment by DotNetNext** [comment]
还有mysql不要查询count

**Comment by DotNetNext** [comment]
where写到splitable前面

**Comment by aaa930811** [comment]
> 那就要合适分表，比如按年

那比如我要查询2022-12-01到2023-01-31的数据，那还是跨表了呀

**Comment by DotNetNext** [comment]
目前是没办法的，跨2个表性能还可以的。只能接受就行
