### ISSUE TITLE
sqlSugar 要长久发展的话，代码要注释一下，没有一句是注释的，只能看文档，或者看源代码

### ISSUE THREAD

**Issue by guo1737** [DotNetNext/SqlSugar#1181]
这个和国外开源的还是有差距的，这个我觉得还是不能省的。

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/3a02caa8-d761-42e0-9ae9-c80997c94323)
你去看一下.NET开源有哪项目有这种热度，目前sqlsugar确实没有时间搞注释，不是我不想，希望可以理解，是目前用户量太多，推动着功能，停不下来，等哪天用户没新需求，这个时候我就有时间整理这些了

**Comment by xyhui83** [comment]
文档足够完善了，用起来很顺手了

**Comment by paxhujing** [comment]
官方文档也不够完善，很多API没有记录或描述清楚。

**Comment by DotNetNext** [comment]
> 官方文档也不够完善，很多API没有记录或描述清楚。

官方文档描述的API绝对是全的，其他没有描述的可以发论坛咨询。文档是按使用者疑问进行完善的。覆盖面是最广的最全的。
