### ISSUE TITLE
mysql 全文索引

### ISSUE THREAD

**Issue by linjiaen** [DotNetNext/SqlSugar#1183]
请问有实现mysql 全文索引语法吗 还是要自己先原生语句

**Comment by DotNetNext** [comment]
可以用扩展函数实现， 也可以用局部SQL   .Where("MATCH(title, description) AGAINST('apple')").ToList()

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.103-preview14
支持了全文索引函数
`db.Queryable<Order>().Where(x => SqlFunc.FullTextContains(x.Name, "a")).ToList()`
如果创建全文索引因为太过复杂暂技术问题支持会比较麻烦需自已创建

**Comment by DotNetNext** [comment]
还有疑问发新的issue
