### ISSUE TITLE
IntoTable中生成SQL有误

### ISSUE THREAD

**Issue by JohnnyQiang** [DotNetNext/SqlSugar#1185]
调用的OutIntoTableSql中 Regex.Split(item, "AS") 不严谨，如果字段名包括AS，这样会误伤字段名，比如字段名为PASS_TIME，生成的sql就是S_TIME了

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.103-preview04
.NET Standard 2.1 已修复，更新04预览版本 ，还有问题发新的
