### ISSUE TITLE
能否引入单元测试框架，提高项目的健壮性？

### ISSUE THREAD

**Issue by WinChance** [DotNetNext/SqlSugar#1187]
我是很支持楼主开源的，但是楼主的单元测试，并没有其他开源项目（如FreeSQL）那么优雅。

**Comment by DotNetNext** [comment]
本地有单元测试，线上只是用户测试用例

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/9b0b6087-9335-4532-ab56-4c4dbb1a8868)

**Comment by DotNetNext** [comment]
多招聘网多看看吧sqlsugar多少岗位
