### ISSUE TITLE
sql server全文索引

### ISSUE THREAD

**Issue by goodnull** [DotNetNext/SqlSugar#1192]
看到有问mysql的全文索引
#1183 
想问下`sql server` 的 `FREETEXTTABLE` 是否支持，怎么写

`SqlFunc.FullTextContains` 生成的sql函数是 `CONTAINS`

**Comment by DotNetNext** [comment]
生成的SQL是对的啊

**Comment by DotNetNext** [comment]
你要先创建全文索引

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/836960ba-7fcf-46d1-9443-feaa7cd2b6c0)
