### ISSUE TITLE
Aop 不支持通过 Ado 直接执行 sql 语句使用记录日志，有地方全局配置吗？

### ISSUE THREAD

**Issue by idea-zone** [DotNetNext/SqlSugar#1197]
``` C#
// 设置 Aop
  db.Aop.OnLogExecuting = (sql, args) =>
            {
                    string log = $"【db0 SQL语句】{UtilMethods.GetSqlString(DbType.PostgreSQL, sql, args)}\n";
                    Console.WriteLine(log );
            };

// 在程序中直接通过 Ado 执行 Sql
var dt = db.Ado.GetDataTable(strSQL, sqlParas)
```

**Comment by DotNetNext** [comment]
支持的

**Comment by DotNetNext** [comment]
多租户需要注意一下用法，还有如果是sqlsugarscope需要注意一下OnLogExecuting 扔的地方

**Comment by idea-zone** [comment]
> 多租户需要注意一下用法，还有是sqlsugarscope需要注意一下OnLogExecuting 扔的地方

可以给个文档的链接吗？感谢大佬。

**Comment by DotNetNext** [comment]
多租户AOP看这个
https://www.donet5.com/Home/Doc?typeId=2246

 SqlSugarClient Db= new SqlSugarClient(new ConnectionConfig(){
           ConnectionString = "连接符字串", 
           DbType = DbType.SqlServer,
           IsAutoCloseConnection = true},
           db=>{  
                    //也可以这里面循环
                   db.GetConnection("1").Aop.OnLogExecuting = (sql, pars) =>
                   {
                     Console.WriteLine("执行1库"+sql);
                   };
                   db.GetConnection("0").Aop.OnLogExecuting = (sql, pars) =>
                   {
                      Console.WriteLine("执行0库"+sql);
                   };
   
  });

**Comment by DotNetNext** [comment]
还有问题发新的Issue ，这个先关闭
