### ISSUE TITLE
描误信息: intemal Error 堆钱信息: at 0raclelntemal.TTC.TTCExecuteSal.ReceiveExecuteResponse

### ISSUE THREAD

**Issue by kaizhou92** [DotNetNext/SqlSugar#1199]
使用ORACLE 数据库  
变更表结构（或者修改视图），新增，删除字段后，查询数据时，会报错，过一会儿就不会出现这个问题

改结构后的几秒内会出现问题，之后就没这个问题了，业务场景是通过改视图动态返回数据

描误信息: intemal Error 堆钱信息: at 0raclelntemal.TTC.TTCExecuteSal.ReceiveExecuteResponse(Accessor1& defineAccessors,Accessor
bindAccessors, Boolean bHasRetumingParams, SQLMetaData& salMetaData, SalStatementType statementType, Int64
noOfRowsFetchedLastTime. nt32 no0fRowsToFetch Int32& no0fRowsFetched. 1nt64& quervld, Int32 longFetchSize, Int64
dlientlntal loBFetchSize.nt64 inita lOBFetchSize, nt64 initialJsONFetchSize. nt641 scnFromExecution.Boolean bAlinputBinds. Int32
arrayBindCount. DataUnmarshaller& dataUnmarshaller. MarshalBindParameterValueHelper& marshalBindParamsHelper. Int6418
(OWSAFfectedByArrayBind.Boolean bDefineDone, Boolean& bMorethanOneRowAfectedByDmWithRetClause, List 1& implicitRsList, Boolear
hl OBArrayFetchReaured at Oraclelnternal.servicebiects OracleCommand mpl.ExecuteReader String commandtext
OracleParameterCollection paramColl. CommandType commandType.
OracleConnectionlmpl connectionlmpl. OracleDataReaderlmpl& rdrlmpl.
nt32 lonaFetchsize. Int64 clientinitiaLOBFs.OracleDependencylmpl orclDependencylmpl.
Int641 scnForExecution.Int641& scnFromExecution
DracleParameterColection& bindByositionParamCol. oolean& bBindParamPresent. Int64& intemallnitiall 0BFS. Int64 intemalnitialJsoNFS
DracleException& exceptionForArayBindDM.. OracleConnection connection. Enumerable 1 adranarsedStmt. Boolean isDescribeOnly.
oolean isFromEF) at OracleManacedDataA ccess Client OracleCommand.ExecuteReader/Boolean reauery. Boolean filReouest
ommandBenavior behavor at Oracle ManagedDataAccess Client OraceCommand.ExecuteDbDataeader CommandBehavior behavior at
ivstem.Data Common.DbCommand Svstem.Data.DbCommand.ExecuteReader/CommandBehavior behavior a

Microsoft AsoNetCore Mvc nfrastructure ActionMeihodExecutor SyncObiectResuliExecutor. Execute(ActionResutvpeMapper maoer
ObiectMethodExecutor executor, Obiect controller. Obiecti arouments at Microsof AsoNetCore Mwc Infrastructure ControllerA ction'nvoker
ounedl12 (Controlleractionlnwoker
elnwokeactionllethodaswncsg
inwoker) at

**Comment by DotNetNext** [comment]
ODP.NET 修改表结构存很大问题，这个驱动就是这样的

**Comment by DotNetNext** [comment]
有一种办法可以解决就是 就是SELECT 中加个随机标识

**Comment by kaizhou92** [comment]
> Oracle.ManagedDataAccess.Core 修改表结构存很大问题，只有将SQL随机加入一串注释才能解决这个问题 另外 视图中不能 * 一定要有明确字段 ，如果表修改那么视图中如果用了*必须重新创建引用的视图

之前在用[Dapper]的时候也是用的Oracle.ManagedDataAccess.Core ，我在想是不是[SqlSugar]存在缓存？

**Comment by DotNetNext** [comment]
长时间未回复，还有问题发新 issues
