### ISSUE TITLE
IsAutoRemoveDataCache相關問題

### ISSUE THREAD

**Issue by Yumitoya8569** [DotNetNext/SqlSugar#1202]
## 問題1
當IsAutoRemoveDataCache打成true時
```C#
//...
MoreSettings = new()
{
   IsAutoRemoveDataCache = true
}
//...
```
Fastest相關操作不會觸發AutoRemoveDataCache
```C#
await _db.Fastest<TableA>().BulkMergeAsync(req);
```
## 問題2
調查源代碼時發現AutoRemoveDataCache的設置在CRUD的實作上都是清除全部快取
而不是依like條件清除與該表格相關的快取, 請問這部分有什麼考量嗎?
```C#
private void AutoRemoveDataCache()
{
   var moreSetts = this.Context.CurrentConnectionConfig.MoreSettings;
   var extService = this.Context.CurrentConnectionConfig.ConfigureExternalServices;
   if (moreSetts != null && moreSetts.IsAutoRemoveDataCache && extService != null && extService.DataInfoCacheService != null)
   {
      this.RemoveDataCache();
   }
}
```

## 討論
以上問題我不確定是byDesign還是bug, 所以諮詢一下
謝謝您

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/2bc01e92-d17c-46ff-af7c-0b8ff4b2b250)

**Comment by DotNetNext** [comment]
支持全局重写

**Comment by DotNetNext** [comment]
`
await _db.Fastest<TableA>().BulkMergeAsync(req);
`
这个我今天支持一下 支持自动RemoveCache

**Comment by DotNetNext** [comment]
我检查了代码 BulkMergeAsync是可以清空二级缓存的

**Comment by DotNetNext** [comment]
```cs
db.Fastest<Order>().RemoveDataCache().BulkMerge(list)
```

**Comment by DotNetNext** [comment]
要这样写

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.113-preview08

升级 已支持 IsAutoRemoveDataCache

**Comment by Yumitoya8569** [comment]
問題1, 已確認新代碼會在End階段清除快取
問題2, 這是我誤會了, 原代碼確實有在上層類依like條件清除快取

謝謝您
