### ISSUE TITLE
How to retrieve data from a SplitTable and join it with an SQL function [dbo].fn_ListDayOfMonth

### ISSUE THREAD

**Issue by mrreddevil2412** [DotNetNext/SqlSugar#1203]
FUNC
```
CREATE function dbo.fn_ListDayOfMonth
(
	@year int = 2023, @month int = 10
)
returns table
as
return 
WITH numbers
as
(
    Select 1 as value
    UNion ALL
    Select value + 1 from numbers
    where value + 1 <= Day(EOMONTH(datefromparts(@year,@month,1)))
)
SELECT convert(varchar(4), @year) + iif(@month<10,'0','') + convert(varchar(2),@month) as NamThang,  datefromparts(@year,@month,numbers.value) day , DATEPART(dw,datefromparts(@year,@month,numbers.value)) as T
FROM numbers

GO

Here's the T-SQL query:


DECLARE @Nam INT = 2023, @Thang INT = 10, @EmployeeId BIGINT = 1627608121918754816

SELECT DK.*
FROM [dbo].fn_ListDayOfMonth(@Nam, @Thang) AS P
JOIN [dbo].[CC_DangKy_20231001] AS DK ON P.NamThang = DK.NamThang AND DK.EmployeeId = @EmployeeId

```

Table: 
<img width="237" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/1c422b4b-45fc-4538-ab02-2c3078a1de26">

**Comment by DotNetNext** [comment]
https://www.donet5.com/Home/Doc?typeId=2315  
There are full time queries

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/6294fcaf-f9e8-493c-9ec5-5bfb6e5aba6f)

**Comment by DotNetNext** [comment]
Post new issues if any

**Comment by mrreddevil2412** [comment]
Special thanks!
I have a question
my table configed
<img width="338" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/313a2796-85a7-46b4-ad10-b15715af1d61">
when Query ....
<img width="800" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/c074be37-c1e1-41f1-901f-103378ffd7ff">
Error
