### ISSUE TITLE
Exception in {"Index was outside the bounds of the array."} When use Join three table

### ISSUE THREAD

**Issue by mrreddevil2412** [DotNetNext/SqlSugar#1204]
qurery linq
<img width="964" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/352bfba8-50e9-4ab8-9dd4-820a8ab2ba26">

Respository Query

<img width="820" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/d4bff16a-654d-4279-a094-47480b30b253">

Exception

<img width="1240" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/3d38ba3c-17a8-47a7-a90a-9229f4361974">

**Comment by DotNetNext** [comment]
Queryable<T1,T2,T3,T4>
```cs
 //error
new JoinInfos(joinType,exp)

//ok
new JoinInfos(joinType,exp,JoinType,exp2,JoinType exp3)
```

**Comment by DotNetNext** [comment]
If there are four tables, then a JOIN operation involves three joins

**Comment by mrreddevil2412** [comment]
I'm join three table and want to return new ApproViewModel

**Comment by mrreddevil2412** [comment]
I'm fixed :)
I forgot, I had to move the select function after the orderby function

**Comment by DotNetNext** [comment]
```
 
db.Queryable<Order, OrderItem, Custom>((o, i, c) => new JoinQueryInfos(
    JoinType.Left, o.Id == i.OrderId,  
    JoinType.Left, o.CustomId == c.Id 
))
.Orderby((o,i,c)=>o.Id)
.Select((o,i,c)=>new ViewModel{ name=o.Name ..})
.ToList()
 
``
OR
```
 
db.Queryable<Order, OrderItem, Custom>((o, i, c) => new JoinQueryInfos(
    JoinType.Left, o.Id == i.OrderId,  
    JoinType.Left, o.CustomId == c.Id 
))

.Select((o,i,c)=>new ViewModel{ name=o.Name ..})
.MergeTable()
.Orderby(it=>it.Name)
.ToList()
 
``
