### ISSUE TITLE
Is there any way to optimize this command?

### ISSUE THREAD

**Issue by mrreddevil2412** [DotNetNext/SqlSugar#1205]
` var whereEx = Expressionable.Create<FeedbackEntity>()
             .And((f) => !f.IsDeleted)
             .And((f) => f.Point < 3 || f.Status != 4)
             .AndIF(offices?.Count > 0, (f) => offices.Select(x => x.Id).Contains(f.UnitID))
             .AndIF(model.StartDate > DateTime.MinValue, (f) => f.CreateTime > model.StartDate)
             .AndIF(model.EndDate > DateTime.MinValue, (f) => f.CreateTime < model.EndDate)
             .AndIF(model.TypeCustomer.IsNotEmptyOrNull(), (f) => model.TypeCustomer.ToInts().Contains(f.TypeCustomer))
             .AndIF(model.TypeFeed.IsNotEmptyOrNull(), (f) => model.TypeFeed.ToInts().Contains(f.TypeFeedback))
             .ToExpression();
 var queryData = await GetFeedbackEntities(whereEx, offices, model);
               
 foreach (var feedbackEntity in queryData)
 {
     feedbackEntity.ProcessHitory = await GetLogFeedbackEntities(feedbackEntity.Id);
     feedbackEntity.VoucherSend = await GetModSendVoucherEntity(feedbackEntity.Id);
     feedbackEntity.LogApprove = await GetApproveFeedbackEntities(feedbackEntity.Id);
     feedbackEntity.Revenue_KHL = await GetRevenueKHL(feedbackEntity.SID);
     feedbackEntity.Revenue_CTV = await GetRevenueCTV(feedbackEntity.IdPartner);
  }`
  ---
  EntityClass
  
<img width="451" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/3db1f11c-9e95-474c-a519-01f6a89dfd31">

Currently, every time I do a for, I have to query to get the dependent object of obj feedbackEntity
So do you have a better way to help me?

**Comment by DotNetNext** [comment]
var list=db.Quyerable<feedbackEntity >().Where(exp)
.Include(x=>x.ProcessHitory )
.Include(x=>x.VoucherSend )
.Include(x=>x.LogApprove )
.ToList();

**Comment by mrreddevil2412** [comment]
> var list=db.Quyerable().Where(exp) .Include(x=>x.ProcessHitory ) .Include(x=>x.VoucherSend ) .Include(x=>x.LogApprove ) .ToList();

Thanks brO!

**Comment by mrreddevil2412** [comment]
Can Includes be used with split tables?
<img width="592" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/9735ed8b-6b83-4f21-8960-5f3989abae1f">
Class Survey

<img width="542" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/acdf712a-9dcb-4498-8feb-cb126bd10b03">

**Comment by DotNetNext** [comment]
`
//填充子对象 
//原理： 数据库一次读取 In (list[0].id,list[1].id,list[2].id...) 内存分配到对应Child
//所以无论集合多少条记录  ThenMapper 只会操作一次库  
db.ThenMapper(treeRoot, item =>
 {   
   //用例1：简单填充  
   //参数解释：子表的ParentId和主表的Id 进行关联查询（有Select写到SetContext前面）
   item.Child = db.Queryable<Tree>().SetContext(x => x.ParentId, () => item.Id, item).ToList();
     
    
   //用例2：可以多属性
   //item.Child=xxxx
   //item.Parent=xxxx
    
     
   //用例3：类型转换类转成DTO （注意：Select中的关联字段要赋值）
   //item.Child = db.Queryable<Tree>()
   //         .Select(it=>new ViewTree(){ParentId=x.ParentId,Id=i.Id,Name=it.Name }) 
   //         .SetContext(x => x.ParentId, () => item.Id, item).ToList();
    
   //用例4：联表填充
   //item.Child=db.Queryable<Tree>()
   //.LeftJoin<Tree>((i,y)=>i.ParentId==y.Id)
   //.Select((i,y)=>new viewmodel(){ Parentid=i.Parentid..........})
   //.SetContext(x => x.ParentId, () => item.Id, item).ToList();
 });
  
`

**Comment by DotNetNext** [comment]
item.Child = db.Queryable<Tree>().**SplitTable().**SetContext(x => x.ParentId, () => item.Id, item).ToList();

**Comment by DotNetNext** [comment]
if async
 
var treeRoot=await db.Queryable<Tree>().ToListAsync(); 
await db.ThenMapperAsync(treeRoot, async item =>
{   
 
   item.Child =await db.Queryable<Tree>().SetContextAsync(x=>x.ParentId,()=>item.Id, item);
});

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.116-preview11 has a major update with split table support for includes

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.116-preview11 has a major update with split table support for includes

**Comment by DotNetNext** [comment]
Update, already supported, there are questions to send new isssues

**Comment by mrreddevil2412** [comment]
> Update, already supported, there are questions to send new isssues
Thanks!

> SqlSugarCore 5.1.4.116-preview11 has a major update with split table support for includes

it so cool.
.
I have a function to import excel. There are 2 columns
Phone and CustomerCode
I need to check before inserting into the table to make sure that record is unique
Can you suggest me which function to use in sqlsugar

**Comment by mrreddevil2412** [comment]
@DotNetNext SplitTable not support Join query???

<img width="1360" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/ed39aad9-de28-4b31-9382-824f1adcc8da">

**Comment by DotNetNext** [comment]
LeftJoin(db.Queryable<T>().Splitable()  ,(x,y)=>x.id==y.xid)

**Comment by mrreddevil2412** [comment]
> LeftJoin(db.Queryable().Splitable() ,(x,y)=>x.id==y.xid)

Thanks,  a tried 
<img width="790" alt="image" src="https://github.com/DotNetNext/SqlSugar/assets/30259651/075502a2-b8e3-4f6c-ada1-767fed019c81">
