### ISSUE TITLE
Illegal mix of collations

### ISSUE THREAD

**Issue by seamusic** [DotNetNext/SqlSugar#1206]
一个很简单的SQL查询语句报错 
Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='

查询的方法如下：
`
           _db.Queryable<SysCodeGenConfig>()
            .Where(u => u.CodeGenId == input.CodeGenId && u.WhetherCommon != YesNoEnum.Y.ToString())
            .Select<CodeGenConfig>()
            .Mapper(u =>
            {
                u.NetType = (u.EffectType == "EnumSelector" || u.EffectType == "ConstSelector" ? u.DictTypeCode : u.NetType);
            })
            .OrderBy(u => u.OrderNo)
`
生成的SQL如下：
`SELECT `Id` AS `Id` ,`CodeGenId` AS `CodeGenId` ,`ColumnName` AS `ColumnName` ,`PropertyName` AS `PropertyName` ,`ColumnLength` AS `ColumnLength` ,`ColumnComment` AS `ColumnComment` ,`NetType` AS `NetType` ,`EffectType` AS `EffectType` ,`FkEntityName` AS `FkEntityName` ,`FkTableName` AS `FkTableName` ,`FkColumnName` AS `FkColumnName` ,`FkColumnNetType` AS `FkColumnNetType` ,`DictTypeCode` AS `DictTypeCode` ,`WhetherRetract` AS `WhetherRetract` ,`WhetherRequired` AS `WhetherRequired` ,`QueryWhether` AS `QueryWhether` ,`QueryType` AS `QueryType` ,`WhetherTable` AS `WhetherTable` ,`WhetherAddUpdate` AS `WhetherAddUpdate` ,`ColumnKey` AS `ColumnKey` ,`DataType` AS `DataType` ,`WhetherCommon` AS `WhetherCommon` ,`DisplayColumn` AS `DisplayColumn` ,`ValueColumn` AS `ValueColumn` ,`PidColumn` AS `PidColumn` ,`OrderNo` AS `OrderNo` FROM `SysCodeGenConfig`  WHERE (( `CodeGenId` = @CodeGenId0 ) AND ( `WhetherCommon` <> CAST(@MethodConst1 AS CHAR)))ORDER BY `OrderNo` ASC `

执行时报错：
"Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '<>'"

如果将u.WhetherCommon != YesNoEnum.Y.ToString() 修改为 u.WhetherCommon != "Y" ，则可以避免这个问题

`
        var query = _db.Queryable<SysCodeGenConfig>()
            .Where(u => u.CodeGenId == input.CodeGenId && u.WhetherCommon != "Y")
            .Select<CodeGenConfig>()
            .Mapper(u =>
            {
                u.NetType = (u.EffectType == "EnumSelector" || u.EffectType == "ConstSelector" ? u.DictTypeCode : u.NetType);
            })
            .OrderBy(u => u.OrderNo);
`

修改后生成的SQL语句如下：
`
SELECT `Id` AS `Id` ,`CodeGenId` AS `CodeGenId` ,`ColumnName` AS `ColumnName` ,`PropertyName` AS `PropertyName` ,`ColumnLength` AS `ColumnLength` ,`ColumnComment` AS `ColumnComment` ,`NetType` AS `NetType` ,`EffectType` AS `EffectType` ,`FkEntityName` AS `FkEntityName` ,`FkTableName` AS `FkTableName` ,`FkColumnName` AS `FkColumnName` ,`FkColumnNetType` AS `FkColumnNetType` ,`DictTypeCode` AS `DictTypeCode` ,`WhetherRetract` AS `WhetherRetract` ,`WhetherRequired` AS `WhetherRequired` ,`QueryWhether` AS `QueryWhether` ,`QueryType` AS `QueryType` ,`WhetherTable` AS `WhetherTable` ,`WhetherAddUpdate` AS `WhetherAddUpdate` ,`ColumnKey` AS `ColumnKey` ,`DataType` AS `DataType` ,`WhetherCommon` AS `WhetherCommon` ,`DisplayColumn` AS `DisplayColumn` ,`ValueColumn` AS `ValueColumn` ,`PidColumn` AS `PidColumn` ,`OrderNo` AS `OrderNo` FROM `SysCodeGenConfig`  WHERE (( `CodeGenId` = @CodeGenId0 ) AND ( `WhetherCommon` <> @WhetherCommon1 ))ORDER BY `OrderNo` ASC 
`
我运行环境是.netcore 8.0 正式版，sqlsugar 5.1.4.118-preview02
请问应该如何修复？

**Comment by seamusic** [comment]
上面没格式，看不清楚，重点就是，linq里的
Where(u => u.WhetherCommon != YesNoEnum.Y.ToString())
会转成 以下语句导致异常
WHERE (WhetherCommon<> CAST(@MethodConst1 AS CHAR))

数据库是mysql 8.0

**Comment by seamusic** [comment]
数据库是 8.0，编码是 utf8mb4，排序规则是：utf8mb4_general_ci
如果使用sqlite则不会出现这个问题

**Comment by DotNetNext** [comment]
主要是这个引起的CAST(@MethodConst1 AS CHAR)   ,解决方案
1、2边都加tostring转成一样编码
2、提ToString()提取到表达式外面
