### ISSUE TITLE
Oracle中INTERVAL DAY TO SECOND数据类型映射TimeSpan, OracleDbBind中MappingTypesConst中应为timespan

### ISSUE THREAD

**Issue by ClintSu** [DotNetNext/SqlSugar#1208]
版本：SqlSugar-5.1.4.127
场景：DbFirst时表中字段类型INTERVAL DAY TO SECOND(6)
Oracle 数据类型映射：https://learn.microsoft.com/zh-cn/dotnet/framework/data/adonet/oracle-data-type-mappings
问题代码：OracleDbBind=> MappingTypesConst=>new KeyValuePair<string, CSharpDataType>("interval day to second",CSharpDataType.@int),

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.128-preview06

**Comment by DotNetNext** [comment]
还有疑问发新的isssue先关闭
