### ISSUE TITLE
If we use IList<T> for Storageable/Insertable/Updatable, sometime may face Newtonsoft.Json.JsonSerializationException

### ISSUE THREAD

**Issue by Zero-Xiong** [DotNetNext/SqlSugar#1209]
Happen to see: If use IList<T>, sometime may face 

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type

but if I changed to List<T>, the error is gone.

For example: 

`public async Task<int> Insert( IList<ClassA> records )
{
    await db.Insertable<ClassA>(records).IgnoreColumns(c => new { c.Column1, c.Column2}).ExecuteCommandAsync(); 
}`

ClassA contains some nested object inside (may have loop reference, like parent - child relationship).

but if changed to List<ClassA>, the error is gone

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.129-preview13 
Already supported, check the preview, the source code is also synchronized

**Comment by DotNetNext** [comment]
Close it first. Post new issues if there are any
