### ISSUE TITLE
sqlserver数据查询的问题

### ISSUE THREAD

**Issue by johnny857** [DotNetNext/SqlSugar#1211]
![image](https://github.com/DotNetNext/SqlSugar/assets/21231884/babfff8c-d300-4d3f-b2ad-c58a2f439ded)

以上为通过linq查询的数据，result无法返回数据 result1能获取到数据。
![image](https://github.com/DotNetNext/SqlSugar/assets/21231884/6f18a46f-1c54-4b04-9dac-1de1f7665e12)

**Comment by DotNetNext** [comment]
看论坛里面的回复，不用2边都发

**Comment by DotNetNext** [comment]
https://www.donet5.com/Ask/9/23706
