### ISSUE TITLE
InsertOrUpdate()函数插入更新遇到的问题

### ISSUE THREAD

**Issue by YuChenDayCode** [DotNetNext/SqlSugar#1214]
我使用的 **sqlite** 调用 **InsertOrUpdate** 函数，在新增操作时，新增成功结果是false。
---
debug了一下，发现新增返回的受影响行数为1，但是更新返回的结果是-1， +=之后结果变成0了，所以变成了false。
![sqlsugar](https://github.com/DotNetNext/SqlSugar/assets/19216741/71584abb-4370-44bc-a4ee-f860f8efbdc8)

---
更新中判断的sql是否为空，查看发现sql是一个换行的转义字符 所以导致返回-1
![Snipaste_2024-01-10_15-19-28](https://github.com/DotNetNext/SqlSugar/assets/19216741/d7e79567-6dd7-4da2-b4e7-619ec49270f8)

麻烦看一下，是否算bug还是我使用方式的问题。谢谢

**Comment by DotNetNext** [comment]
你是questdb吗

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.133-preview08  勾一下预览版本已修复  （等5分钟）
