### ISSUE TITLE
Operand type clash: time is incompatible with float 

### ISSUE THREAD

**Issue by mrreddevil2412** [DotNetNext/SqlSugar#1215]
[ERROR Message]： Operand type clash: time is incompatible with float 
[TYPE]： SqlException 
[ERROR INFO]： Operand type clash: time is incompatible with float 
[ERROR LINE]：    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

**Comment by DotNetNext** [comment]
[SugarColumn(IsNullable = true, ColumnDataType = "float")]
public TimeSpan? SoGio { get; set; }

Change to

[SugarColumn(IsNullable = true, ColumnDataType = "time")]
public TimeSpan? SoGio { get; set; }
