### ISSUE TITLE
查询和增删改查方面的改进

### ISSUE THREAD

**Issue by AlexScofield** [DotNetNext/SqlSugar#1220]
在使用达梦数据库时:
1.查询:  Queryable<Table>().Where(x => ids.Contains(x.Id)).ToList();时,如果ids是个空List会报错,底层能否判断下直接返回空列表而不是报错?
2. Updateable(datas).ExecuteCommand();//如果datas是空List也会报错,能否底层返回0行受影响而不是抛出异常?否则每次调用前都需要判断参数,很烦,而且很容易忘记判断.(同理 Updateable,Deletable...)

**Comment by DotNetNext** [comment]
ids是空不会报错，只有null才报错

**Comment by DotNetNext** [comment]
你指的是NULL还是空

**Comment by AlexScofield** [comment]
> ids是空不会报错，只有null才报错

ids=new List<int>();
测试了一下,在windows上是正常的,但是在linux下面就会报错:
Sequence contains no elements. 不知道啥原因

**Comment by DotNetNext** [comment]
sqlsugar升级最新版本看看

**Comment by DotNetNext** [comment]
最新版本更新了达梦驱动

**Comment by DotNetNext** [comment]
因为其他人也正常的，ids.Contains这个语法又是达梦一个库的，会不是你逻辑有问题
