### ISSUE TITLE
linux  sqlserver 08 下关联查询返回匿名类型时慢

### ISSUE THREAD

**Issue by shenglingshi** [DotNetNext/SqlSugar#1224]
同一个ISugarQuerable关联表达式，当查询返回 匿名类型与 直接返回实体类列表时，
两个关联表数据量都不大，一个2K左右，一个3W左右，查询结果数据集大概1K-2K之间
windows下速度很快，但是Linux下速度很慢，差异很大。
环境：docker mcr.microsoft.com/dotnet/aspnet:5.0 镜像+NET5+SqlServer2008+SqlSugar5.1.4.59+ToArrayAsync()方法获取数据

![企业微信截图_1708487964769](https://github.com/DotNetNext/SqlSugar/assets/998503/0fa93ba3-386c-482a-9d2b-fd6b46336024)

**Comment by DotNetNext** [comment]
升级最新试试

**Comment by shenglingshi** [comment]
好的。

**Comment by shenglingshi** [comment]
> 升级最新试试

我们的 Sql Server 2008 是部署在Windows 下的，程序跑在Linux的镜像里。

**Comment by DotNetNext** [comment]
建议用sqlsever 2017+在Linux ，如果还有问题提供远程字符串可以重现的DEMO

**Comment by DotNetNext** [comment]
另外sqlsugar要升级最新

**Comment by shenglingshi** [comment]
> 建议用sqlsever 2017+在Linux ，如果还有问题提供远程字符串可以重现的DEMO
好的，感谢百忙之中回复。

**Comment by DotNetNext** [comment]
还有疑问吗？

**Comment by DotNetNext** [comment]
时间长未回复，还有疑问发新的issue
