### ISSUE TITLE
导航 到的表是分表 ，能不能在查询的时候 让我自定义分表 

### ISSUE THREAD

**Issue by leida1983** [DotNetNext/SqlSugar#1227]
var list = db.Queryable<StudentA>()
.Includes(x => x.Books)
.ToList();

比如用上面的例子 Books  如果是 SplitTable 的时候，我希望后面可以定义 分表的范围 .SplitTable(tabs => tabs.Take(3))
这样子 来缩小查询范围

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.146-preview03
更新到这个版本

using SqlSugar.SplitTableExtensions

var list = db.Queryable()
.Includes(x => x.Books.SplitTable(x=>x.Take(1)).ToList() )
.ToList();
