### ISSUE TITLE
sql does not interrupt execution

### ISSUE THREAD

**Issue by domiuns** [DotNetNext/SqlSugar#1228]
your code is as follows
``` C#
await ((DbDataReader) dataReader).ReadAsync() 
```
The ReadAsync method does not give `CancellationToken` parameter

When the client actively cancels the request, sql continues to execute and does not interrupt execution

Code Version:5.1.4.146
DB:SqlServer

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.147-preview11    Just updated

**Comment by DotNetNext** [comment]
Source code is also synced

**Comment by DotNetNext** [comment]
If there are more questions, send a new isssue
