### ISSUE TITLE
使用 ExecuteReturnBigIdentityAsync 保存数据报  Object cannot be cast from DBNull to other types.

### ISSUE THREAD

**Issue by awfi1986** [DotNetNext/SqlSugar#1229]
在mysql中使用正常 到sqlserver里使用就报错了 是因为主键不是自增长  mysql获取自增ID函数返回 0 sqlserver则返回NULL 导致转成long报错了

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.147-preview13 已支持，过五分钟后安装 ，还有疑问发新贴子
