### ISSUE TITLE
使用sqlsugar调用 Kdbndp 带 数组参数的 存储过程

### ISSUE THREAD

**Issue by xiaoentiy** [DotNetNext/SqlSugar#1230]
因项目需求需要使用sqlsugar调用 Kdbndp 带 数组参数的 存储过程。
过程代码如下：
CREATE OR REPLACE PROCEDURE TestProc(menus string[])
AS 
BEGIN
   -- 业务逻辑 游标处理
   SELECT  c1;
END;
使用SqlSugarCore.Kdbndp 8.3.715 调用代码 怎么调用都将参数传递不进去，请大神们施以援手。

**Comment by DotNetNext** [comment]
IsArray=true 
加了吗

**Comment by DotNetNext** [comment]
还有疑问吗？

**Comment by xiaoentiy** [comment]
按照你说的更改，已经好了噶，感谢
