### ISSUE TITLE
PostgreSql Insertable 一串 List 的时候， 9999-12-31 23:59:59.999999 会变成 "10000-01-01 00:00:00"

### ISSUE THREAD

**Issue by idea-zone** [DotNetNext/SqlSugar#1233]
环境： pg12 ，SqlSugar 5.1.4.86 ， NET5

###### 数据库结构： 
![image](https://github.com/DotNetNext/SqlSugar/assets/53116704/46bbb0bf-9a44-4dad-beff-2327ec69fe54)

###### model
~~~ C#
class Test1{

    public DateTime StartDateTime { get; set; } = DateTime.MinValue;
    public DateTime EndDateTime { get; set; } = DateTime.MinValue;
}
~~~

###### 当只插入一条时，数据正常
~~~C#
 List<Test1> result = new List<Test1>();


            var rst = new Test1
            {
                StartDateTime = DateTime.MinValue, // 最早聊天时间
                EndDateTime = DateTime.MaxValue, // 最晚聊天时间
            };

            result.Add(rst);
            Context.Insertable(result).ExecuteCommand();
       
~~~
数据库的值
![image](https://github.com/DotNetNext/SqlSugar/assets/53116704/2acffe47-f0a5-4162-a00d-6c7953504688)

###### 当批量插入多条时，数据不正常
~~~C#
 List<Test1> result = new List<Test1>();


            var rst = new Test1
            {
                StartDateTime = DateTime.MinValue, // 最早聊天时间
                EndDateTime = DateTime.MaxValue, // 最晚聊天时间
            };

           var rst = new Test1
            {
                StartDateTime = DateTime.MinValue, // 最早聊天时间
                EndDateTime = DateTime.MinValue, // 最晚聊天时间
            };

            result.Add(rst);
            Context.Insertable(result).ExecuteCommand();
~~~
![image](https://github.com/DotNetNext/SqlSugar/assets/53116704/69d2cded-127e-403e-a1f0-05774e065d01)

**Comment by DotNetNext** [comment]
好的我处理一下

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.153-preview06
勾一下预览已修复

**Comment by DotNetNext** [comment]
还有问题吗

**Comment by idea-zone** [comment]
> 还有问题吗

~~~ 报错
System.Exception : 中文提示 : StartDateTime绑定到Test1失败,可以试着换一个类型，或者使用ORM自定义类型实现
English Message : MfImFriendChatSum StartDateTime bind error

  堆栈跟踪: 
SqlSugarEntity(IDataRecord )
IDataReaderEntityBuilder`1.Build(IDataRecord dataRecord)
DbBindAccessory.GetEntityList[T](SqlSugarProvider context, IDataReader dataReader)
DbBindProvider.DataReaderToList[T](Type type, IDataReader dataReader)
QueryableProvider`1.GetData[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
QueryableProvider`1.GetData[TResult](KeyValuePair`2 sqlObj)
QueryableProvider`1._ToList[TResult]()
QueryableProvider`1.ToList()
SqlSugarTest.Test_Batch_Insert()
~~~

数据源：
![image](https://github.com/DotNetNext/SqlSugar/assets/53116704/ea588ec7-ddfa-4137-87f2-a07f951f1f75)

已经开启了 Infinity DateTime 
![image](https://github.com/DotNetNext/SqlSugar/assets/53116704/c4a8a6ef-1665-4eda-83c1-c757b15928ac)

**Comment by idea-zone** [comment]
> > 还有问题吗
> 
> ```
> System.Exception : 中文提示 : StartDateTime绑定到Test1失败,可以试着换一个类型，或者使用ORM自定义类型实现
> English Message : MfImFriendChatSum StartDateTime bind error
> 
>   堆栈跟踪: 
> SqlSugarEntity(IDataRecord )
> IDataReaderEntityBuilder`1.Build(IDataRecord dataRecord)
> DbBindAccessory.GetEntityList[T](SqlSugarProvider context, IDataReader dataReader)
> DbBindProvider.DataReaderToList[T](Type type, IDataReader dataReader)
> QueryableProvider`1.GetData[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
> QueryableProvider`1.GetData[TResult](KeyValuePair`2 sqlObj)
> QueryableProvider`1._ToList[TResult]()
> QueryableProvider`1.ToList()
> SqlSugarTest.Test_Batch_Insert()
> ```
> 
> 数据源： ![image](https://private-user-images.githubusercontent.com/53116704/322332630-ea588ec7-ddfa-4137-87f2-a07f951f1f75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTM3MzAsIm5iZiI6MTcxMzE1MzQzMCwicGF0aCI6Ii81MzExNjcwNC8zMjIzMzI2MzAtZWE1ODhlYzctZGRmYS00MTM3LTg3ZjItYTA3Zjk1MWYxZjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAzNTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyM2MxNGIzNWU1NzllNTkwYjlkYmJmODNjOWE2OGUwM2VhMGM4Njg0ZWM1MDQ5Mjg0ZWExYjI3MDQyNzM4NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jmIdTPxC0xdMVvT5-C0EsYpIM3olOXUmQinvXpw58sM)
> 
> 已经开启了 Infinity DateTime ![image](https://private-user-images.githubusercontent.com/53116704/322332786-c4a8a6ef-1665-4eda-83c1-c757b15928ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTM3MzAsIm5iZiI6MTcxMzE1MzQzMCwicGF0aCI6Ii81MzExNjcwNC8zMjIzMzI3ODYtYzRhOGE2ZWYtMTY2NS00ZWRhLTgzYzEtYzc1N2IxNTkyOGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAzNTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMjAzOWIyZmRjMWQ0Yzc4NzM0M2M0MWUxY2NmZGFjYzQ2MDQ5MDM4MTIwMTMxM2Q0ZGZkMmM1Y2RhM2IzNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YkgIHKIOZ7bIBHv4XKvPYihUt96gf87Hyi4iMO6ovN0)

重新构建表测试没问题，这个先关闭了。
