### ISSUE TITLE
操作数类型冲突: uniqueidentifier 与 bigint 不兼容

### ISSUE THREAD

**Issue by xiaochanghai** [DotNetNext/SqlSugar#1236]
提示： 操作数类型冲突: uniqueidentifier 与 bigint 不兼容

方法：await _db.Queryable<TEntity>().WithCacheIF(blnUseCache, 10).In(objId).SingleAsync()
objId 是guid类型

不知道如何解，麻烦作者赐教 谢谢
![image](https://github.com/DotNetNext/SqlSugar/assets/25529268/8d644bd3-cd52-4075-869c-cd80c986e2b0)

实体主键是guid类型

**Comment by DotNetNext** [comment]
问题描述清楚
1、数据库是什么？
2、objId是什么类型
3、数据库主键是什么类型

**Comment by xiaochanghai** [comment]
> 问题描述清楚 1、数据库是什么？ 2、objId是什么类型 3、数据库主键是什么类型 4、错误的 message是什么

数据库是 sql server
objId是guid
数据库主键是guid
错误的 message是操作数类型冲突: uniqueidentifier 与 bigint 不兼容

**Comment by DotNetNext** [comment]
截图具体错误

**Comment by xiaochanghai** [comment]
> 截图具体错误

![image](https://github.com/DotNetNext/SqlSugar/assets/25529268/9eb24257-d1b9-44fb-b2d9-289076c3a83b)

**Comment by DotNetNext** [comment]
```cs
db.CodeFirst.InitTables<Uniatafa>();//建表
object id1 = Guid.NewGuid();
db.Insertable(new Uniatafa() { Name = "a", xx = (Guid)id1 }).ExecuteCommand();
var list = db.Queryable<Uniatafa>().InSingleAsync(id1).GetAwaiter().GetResult();
 public class Uniatafa
 {
     [SugarColumn(IsPrimaryKey =true)]
     public Guid xx { get; set; }
     public string Name { get; set; }
 }
```
不能重现你说的问题，上面测试用例 写一个可以重现的 DEMO

**Comment by DotNetNext** [comment]
我怀疑是你数据库类型有问题可能你数据库是 bigint

**Comment by xiaochanghai** [comment]
> ```cs
> db.CodeFirst.InitTables<Uniatafa>();//建表
> object id1 = Guid.NewGuid();
> db.Insertable(new Uniatafa() { Name = "a", xx = (Guid)id1 }).ExecuteCommand();
> var list = db.Queryable<Uniatafa>().InSingleAsync(id1).GetAwaiter().GetResult();
>  public class Uniatafa
>  {
>      [SugarColumn(IsPrimaryKey =true)]
>      public Guid xx { get; set; }
>      public string Name { get; set; }
>  }
> ```
> 
> 不能重现你说的问题，上面测试用例 写一个可以重现的 DEMO

好的 我试试 谢谢

**Comment by xiaochanghai** [comment]
> 我怀疑是你数据库类型有问题可能你数据库是 bigint
数据库是guid的 这个可以确定 数据库是老项目设计好的

**Comment by DotNetNext** [comment]
那就需要DEMO了，不能重现
