### ISSUE TITLE
有增加国产数据库yashandb的计划吗

### ISSUE THREAD

**Issue by aaa930811** [DotNetNext/SqlSugar#1240]
有增加国产数据库yashandb的计划吗？

**Comment by DotNetNext** [comment]
你用mysql试试

**Comment by DotNetNext** [comment]
```cs
 
 SqlSugarClient db = new SqlSugarClient(new ConnectionConfig()
 {
       DbType = DbType.MySql,
       ConnectionString ="server=localhost;Database=SqlSugar4xTest;Uid=root;Pwd=haosql",
       IsAutoCloseConnection = true
 });
 //个别特殊的数据库需要禁用Nvarchar(标题4)
```

**Comment by aaa930811** [comment]
试过了不行，数据库连不上中文提示 :  连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，错误信息：Connect Timeout expired.DbType="MySql";ConfigId="".
English Message : Connection open error . Connect Timeout expired.DbType="MySql";ConfigId="" ”

**Comment by DotNetNext** [comment]
> 试过了不行，数据库连不上 中文提示 : 连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，错误信息：Connect Timeout expired.DbType="MySql";ConfigId="". English Message : Connection open error . Connect Timeout expired.DbType="MySql";ConfigId=""
你可以提供远程链接 给我测试 。可以加我好友。

**Comment by DotNetNext** [comment]
改线下沟通，目前可以使用ODBC
