### ISSUE TITLE
SampleBy方法中的SampleByUnit 有bug，sampleBy.ToString().Substring(0, 1).ToLower()这个如果是Month，会按照分钟计算

### ISSUE THREAD

**Issue by syp10000** [DotNetNext/SqlSugar#1241]
SampleBy方法中的SampleByUnit 有bug，sampleBy.ToString().Substring(0, 1).ToLower()这个如果是Month，会按照分钟计算

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.155-preview16 已修复

**Comment by DotNetNext** [comment]
勾一下预览

**Comment by DotNetNext** [comment]
还有问题，如果没有问题就关闭了

**Comment by syp10000** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/76423924/679a2308-8e14-482a-b6d5-e40575beb27e)
这里的毫秒，微妙呢

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.155-preview18
枚举加了 微秒和毫秒，过五分钟后更新 预览

**Comment by syp10000** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/76423924/543b93f6-95f0-4389-ab39-0f0fe7e17cb2)

怎么感觉对QuestDB支持不太好啊，这里有Latest On吗？

**Comment by DotNetNext** [comment]
https://www.donet5.com/Home/Doc?typeId=2434
文档：标题9 支持latest on

**Comment by syp10000** [comment]
SAMPLE BY 支持 ALIGN TO吗？

**Comment by DotNetNext** [comment]
> SAMPLE BY 支持 ALIGN TO吗？
不是有字符串重载吗，不用枚举

**Comment by DotNetNext** [comment]
还有问题吗

**Comment by DotNetNext** [comment]
还有疑问发新的issue，先关闭。
