### ISSUE TITLE
DBFrist產生出來的Class名稱跟屬性名稱相同

### ISSUE THREAD

**Issue by flier268** [DotNetNext/SqlSugar#1242]
```C#
sugarClient.DbFirst.IsCreateAttribute().StringNullable().IsCreateDefaultValue().CreateClassFile("D:\\Test");
```

因為既有的table名稱與屬性名稱相同，但是C#不允許class名稱跟屬性名稱相同，我只有找到用正則修改名稱的方法，但還是沒辦法在唯獨兩者衝突的時候才修改的方法，有解嗎？

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/e92dc2c2-fef1-4a52-b852-237da7dab7df)

**Comment by flier268** [comment]
我目前暫時的解法就是用這個，將Table都加上"Table_"的前墜，因為好像沒有函數可以同時判斷table名稱跟屬性名稱，用以決定屬性名稱

**Comment by DotNetNext** [comment]
dbfirst只能表名和字段名。。肯定有规律的，比如去下划线等

**Comment by DotNetNext** [comment]
还有疑问发新的issue
