### ISSUE TITLE
使用ODBC连接的时候可以成功连接，但是不能读取数据

### ISSUE THREAD

**Issue by JimmyTsai75** [DotNetNext/SqlSugar#1253]
db = new SqlSugarClient(new ConnectionConfig()
                {
                    DbType = DbType.Odbc,
                    ConnectionString = "Dsn=SendMail;DataBase=SqlEmail;",
                    IsAutoCloseConnection = true,
                    AopEvents = new AopEvents
                    {
                        OnLogExecuting = (sql, p) =>
                        {
                            Console.WriteLine(sql);
                        }
                    }
                });
                
                执行db.Queryable<T>().ToList() 会一直等待，也不报错

**Comment by JimmyTsai75** [comment]
测试连接状态都是可以的，conn.State显示是 System.Data.ConnectionState.Open

**Comment by DotNetNext** [comment]
你是不是winform用了异步方法导致卡了界面  ，winfrom中用异步方法要加async 
 还有问题需要像模版一样提供demo
https://www.donet5.com/Home/Doc?typeId=2366

**Comment by DotNetNext** [comment]
还有问题吗？

**Comment by DotNetNext** [comment]
长时间未回复，先关闭，有问题在发新的issue
