### ISSUE TITLE
加一个 find_in_set 我怎么没有找到

### ISSUE THREAD

**Issue by Messilimeng** [DotNetNext/SqlSugar#1254]
![image](https://github.com/DotNetNext/SqlSugar/assets/12272166/9d6fcd1f-2d31-4004-b32e-c15ced135ac5)

**Comment by DotNetNext** [comment]
主要是这个语法其他数据库不支持

SqlFunc.SplitIn("1,2,3","3")  返回true，你看看这个函数能满足你不

**Comment by DotNetNext** [comment]
还有疑问吗？

**Comment by Messilimeng** [comment]
@DotNetNext 没有了 谢谢
