### ISSUE TITLE
enum如果資料庫格式為字串，但不是枚舉名字本身

### ISSUE THREAD

**Issue by flier268** [DotNetNext/SqlSugar#1256]
如果我資料儲存"0" "1"(資料庫格式為字串)，而不是enum的名字，實體使用enum，要怎麼用
```C#
public enum Status
{
    /// <summary>
    /// 未編輯(on server: 已退回)
    /// </summary>
    [EnumMember(Value = "0")]
    NotEdited = 0,

    /// <summary>
    /// 編輯中
    /// </summary>
    [EnumMember(Value = "1")]
    Editing = 1,

    /// <summary>
    /// 待上傳(on server: 待核准)
    /// </summary>
    [EnumMember(Value = "2")]
    WaitForUpload = 2,
}
```

public  Status Status { get; set; }

**Comment by DotNetNext** [comment]
https://www.donet5.com/Home/Doc?typeId=2415
看标题4  ，你可能通过反射拿备注

**Comment by flier268** [comment]
可以看懂，但這樣寫調用很麻煩，而且我想要用AOT，如果要用BulkMergeAsync就不能這樣用了吧？
更傾向於如果有EnumMember就用他的Value，EF Core也是這樣用的

**Comment by DotNetNext** [comment]
没听懂你说的，BulkMergeAsync 是更新 。和备注有什么关系

**Comment by DotNetNext** [comment]
不是很理解你这样的意义
 [EnumMember(Value = "0")]
    NotEdited = 0,   这2值不一样的吗

**Comment by DotNetNext** [comment]
sqlsugar插入 默认插入的是 value不是name

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/d626bfab-3dfa-49f2-8117-76c0a3f9cc3c)
我AOT测试了数据库都是INT 不是字符串

**Comment by flier268** [comment]
因為資料庫欄位是字串，但是存數字的字串形式，不要問我為什麼這樣設計，我也不明白
enum是數值，不是字串

**Comment by DotNetNext** [comment]
现在就是存的数字  ，默认sqlsugar插入枚举存在库就是数字

**Comment by DotNetNext** [comment]
没听懂你需求

**Comment by DotNetNext** [comment]
/// <summary>
    /// 未編輯(on server: 已退回)
    /// </summary>
    [EnumMember(Value = "0")]
    NotEdited = 0

这个默认存到库是0，你想要结果是什么？

**Comment by flier268** [comment]
我想要存"0"，不是0
vchar

**Comment by DotNetNext** [comment]
> 我想要存"0"，不是0 vchar
这2个值不一样的吗，你数据库是字符串，存到库就0

**Comment by DotNetNext** [comment]
主要看表的类型

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/230654f4-9238-43f8-946f-b061bcac70a7)
我测试varchar也能插入进去

**Comment by flier268** [comment]
如果要改存a是不是就不行了

**Comment by DotNetNext** [comment]
如果真用到可以用自定义类型实现
https://www.donet5.com/Home/Doc?typeId=2542
