### ISSUE TITLE
SqlSugar 使用 ODBC 连接 SQL Server 2008 ，调用存储过程无法返回查询数据

### ISSUE THREAD

**Issue by Yoodanet** [DotNetNext/SqlSugar#1261]
DotNetNext 你好，我刚使用SqlSugar的api调用存储过程查询数据，无法返回查询的数据。代码如下：

.Ado.UseStoredProcedure().SqlQuery<customer>("getcustomer", new { id= "1000"});
     
返回的记录数量为0。 使用 GetDataTable 就可以返回数据。

麻烦帮助查看一下，谢谢！！！

**Comment by DotNetNext** [comment]
这个不应该的，因为底层几乎一个方法

**Comment by Yoodanet** [comment]
可能是传参的问题，我刚试了下面的代码也不行：
.Ado.UseStoredProcedure().GetDataTable("getcustomer", new { type = "update_status_d1", doc_no = tlNumber });
但是如果是拼接的SQL 语句就可以，比如“exec getcustomer @type='asdf' ” ，这样就可以。

**Comment by DotNetNext** [comment]
那就是ODBC不支持 UseStoredProcedure

**Comment by DotNetNext** [comment]
只能exec写法

**Comment by DotNetNext** [comment]
你可以用 db.ado.sqlquery("exec xxx  @p",new {p=1})

**Comment by Yoodanet** [comment]
我查看了一下资料，ODBC调用存储过程的格式应该为 “{CALL sp_name(?)}” , 咱们的Sqlsugar是这样解析的吗？麻烦帮助确认一下。
{CALL sp_name(?,?)} ： 小括号里的问号代表参数。

**Comment by DotNetNext** [comment]
这个是odbc驱动处理

**Comment by DotNetNext** [comment]
我这边处理不了具体格式

**Comment by DotNetNext** [comment]
我这边只能指定CommandType=存储过程

**Comment by DotNetNext** [comment]
还有问题吗？没有问题我就关闭了。

**Comment by Yoodanet** [comment]
嗯嗯，关闭吧。谢谢！
