### ISSUE TITLE
to many parameters

### ISSUE THREAD

**Issue by ricoisme** [DotNetNext/SqlSugar#1262]
請教一下
使用下面程式碼進行無主鍵刪除，當dictionary數量太多會發生 to many parameters 的錯誤，
是否有其他寫法呢?還是如何避免? 
謝謝

 var dcs = _sqlSugarClient.Utilities.DataTableToDictionaryList(dt);
 var total = await _sqlSugarClient.Deleteable<object>().AS(fullTableName)
     .WhereColumns(dcs).ExecuteCommandAsync();
 return total;

**Comment by DotNetNext** [comment]
db.Utilities.PageEachAsync(allList, 100 ,async pageList=> {
      await  xxxxxxx.WhereColumns(pageList)ExecuteCommandAsync();
});

**Comment by DotNetNext** [comment]
非实体操作可以这样分页， 实体操作支持就直接能用.Deleteable.PageSize

**Comment by ricoisme** [comment]
感謝
