### ISSUE TITLE
SqlSugar 使用 ODBC 连接 SQL Server 2008, 使用批量插入Api  InsertRangeAsync(listObj) 出错

### ISSUE THREAD

**Issue by Yoodanet** [DotNetNext/SqlSugar#1266]
DotNetNext 你好，
使用InsertAsync(obj) 可以正常插入数据，但是批量插入的时候就会报错：
ERROR [42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]無效的物件名稱 'dual'。

请帮助确认，谢谢！

**Comment by DotNetNext** [comment]
这个我处理一下，以前odbc只是针对oracle的

**Comment by DotNetNext** [comment]
SqlSugar.OdbcCore 5.1.4.163

已修复

**Comment by Yoodanet** [comment]
> SqlSugar.OdbcCore 5.1.4.163
> 
> 已修复

收到！我测试一下。

**Comment by DotNetNext** [comment]
可以了吗

**Comment by Yoodanet** [comment]
> 可以了吗

可以批量插入了。非常感谢！！！
