### ISSUE TITLE
分表BUG

### ISSUE THREAD

**Issue by caijie17780520163** [DotNetNext/SqlSugar#1267]
![微信图片_20240710122245](https://github.com/DotNetNext/SqlSugar/assets/12708456/cd360fc5-d58a-45dc-bf36-4864b4004be2)
临近00点的时候会在8号表插入9号的数据

**Comment by caijie17780520163** [comment]
DotNetNext 你好， 请帮助确认一下  是否有此BUG

**Comment by DotNetNext** [comment]
你设置分表字段了吗？不存在你这种情况。因为插入哪个表是按你的时间字段来的

**Comment by DotNetNext** [comment]
CreateTime设置分表字段后，你这个时间是 传多少就插入哪个表，你也可以向前插入和向后插入。

**Comment by caijie17780520163** [comment]
> CreateTime设置分表后，你这个时间是传递多少就插入哪个表，您还可以向前插入和向后插入。

![image](https://github.com/DotNetNext/SqlSugar/assets/12708456/d4125759-20db-4bcd-91d2-0ce373276825)设置了分表字段的呀

**Comment by DotNetNext** [comment]
还有疑问提供完整可以重现的DEMO,因为这个是按时间存储的，你传什么就存什么，你几点就进哪个表

**Comment by DotNetNext** [comment]
还有一种可能就是你这个工具不准，用ORM查询出来看看

**Comment by DotNetNext** [comment]
长时间未回复，还有疑问发新的ISSUE
