### ISSUE TITLE
OpenTelemetry support

### ISSUE THREAD

**Issue by ZUOXIANGE** [DotNetNext/SqlSugar#1269]
Could this ORM support OpenTelemetry (including tracing, metrics, and logs)?

The following link helps with how to implement it.

https://opentelemetry.io/docs/languages/net/instrumentation/

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.EntityFrameworkCore/README.md

**Comment by DotNetNext** [comment]
https://www.donet5.com/Home/Doc?typeId=1204   
Support for differential logging, various AOP
Wait a few days to translate to wiki

**Comment by DotNetNext** [comment]
https://github.com/DotNetNext/SqlSugar/wiki/b2.Aop-Audit-log
https://github.com/DotNetNext/SqlSugar/wiki/b2.Aop%E2%80%90Data-events
If there are any questions that have been translated, please send a new isssue communication
