### ISSUE TITLE
使用UpdateSql批量更新出错

### ISSUE THREAD

**Issue by domiuns** [DotNetNext/SqlSugar#1270]
![image](https://github.com/user-attachments/assets/ce4b7669-1c1d-424e-a340-e8b4ca19c0d6)

![image](https://github.com/user-attachments/assets/45456e6a-891e-49d8-960a-6770b05d6fd3)

**Comment by domiuns** [comment]
![image](https://github.com/user-attachments/assets/77b47d21-c4a5-47a2-be26-38cf6bd20427)

**Comment by DotNetNext** [comment]
批量UpdateSql这个特性暂还不支持，这个今天处理一下。

**Comment by DotNetNext** [comment]
```cs
 db.Updateable(updateObjs)
                     .PublicSetColumns(it => it.Name, it => it.Name + "a")
                     .ExecuteCommand();
```
改成这样 实体特性删掉  ，不要用特性

**Comment by domiuns** [comment]
@DotNetNext 这样改动的地方太多了

**Comment by DotNetNext** [comment]
> @DotNetNext 这样改动的地方太多了

主要这个批量不是很好改

**Comment by DotNetNext** [comment]
不符合批量插入规范了。

**Comment by domiuns** [comment]
@DotNetNext 我的目的是用UpdateSql这个特性来个这个列赋值自定义函数的。或者有其他办法，让我做很小的更改，达到我的目的。

**Comment by domiuns** [comment]
@DotNetNext 或者可以新加一个特性属性，更新时使用 Set Num=DefineFuc(Name) ,而不将该列生成到 Update Select中

**Comment by DotNetNext** [comment]
![image](https://github.com/user-attachments/assets/90692382-2405-4f0d-b12d-e88ce1463ad9)

这个是有前缀的不太好改。

**Comment by DotNetNext** [comment]
db.Updateable(updateObjs)
                     .PublicSetColumns(it => it.Num, it => it.Num+ 1)//删掉UpdateSql
                     .ExecuteCommand();

这个怎么也比写SQL快

**Comment by domiuns** [comment]
@DotNetNext 其实我的场景是调用SqlServer的CheckSum函数

**Comment by DotNetNext** [comment]
那就先这样，后面我想到了方案在想办法支持。
