### ISSUE TITLE
The column name 'sugarIndex' does not exist in the result set.

### ISSUE THREAD

**Issue by shengguow** [DotNetNext/SqlSugar#1272]
原本都运行的好好的，
手动在其他不相关的 Table 加入栏位 Sort 之后，
突然跳出这个讯息，手动 Drop table 重新 InitializeTables()，也同样问题，请求协助感恩。

执行下列程序码出错:
==================================================
var sqlString = (_client.Queryable<DateOfMenuDetail>().SplitTable(t => t.ContainsTableNames(GlobalVariables.TableRange("DATE_OF_MENU_DETAIL"))).ToSqlString());

出现的错误讯息:
The column name 'sugarIndex' does not exist in the result set.

作业环境:
Windows IIS Express (本地端)
MySQL  8.0.30
ASP.NET Core 8.0
[Report.zip](https://github.com/user-attachments/files/16343823/Report.zip)

**Comment by shengguow** [comment]
手动在 MENU 的资料库、MENU_DETAIL 各都加入 Sort 栏位后(非透过 InitializeTable 调整栏位)，
(_client.Queryable().SplitTable(t => t.ContainsTableNames(GlobalVariables.TableRange("DATE_OF_MENU_DETAIL"))).ToSqlString());
就出问题了

**Comment by DotNetNext** [comment]
是最新版本吗

**Comment by DotNetNext** [comment]
不是很明白你说的什么意思 。你可以写一个DEMO ，可以重现的

**Comment by shengguow** [comment]
可以私下把整个专案传给您们吗?
找不到原因，无法重制问题
(PS: 您们回复的效率太恐怖了)

**Comment by DotNetNext** [comment]
搞个可以重现的DEMO发我邮箱 610262374@qq.com

**Comment by shengguow** [comment]
哈囉 寄到您信箱了，感恩。

**Comment by shengguow** [comment]
试过 _client.Ado.SqlQuery<object>(sql, sqlParameters.ToArray()).ToList() 可以查询回资料
但改用 _client.Ado.SqlQuery<DateOfMenuDetail>(sql, sqlParameters.ToArray()).ToList()

就会出现  the column name 'sugarIndex' does not exist in the result set.

求助 感恩。

**Comment by DotNetNext** [comment]
![image](https://github.com/user-attachments/assets/474f82fa-3aa9-4cec-bd85-a5bf84e6201e)

这样就好了，应该和你的AOP什么东西冲突。具体的我也没有细的研究，你这个DEMO太复杂了

**Comment by shengguow** [comment]
可以了，謝謝您！
具體問題我再找一下就好，感恩。

**Comment by DotNetNext** [comment]
好的，有问题在发新的issue这个就关闭了

**Comment by shengguow** [comment]
OK 太恐怖的效率了
