### ISSUE TITLE
SqlSugar 使用 ODBC 连接 SQL Server 2008 ， 使用GetPageListAsync 参数中使用Contains 函数出错。

### ISSUE THREAD

**Issue by Yoodanet** [DotNetNext/SqlSugar#1275]
你好 DotNetNext，

我调试了下源码，发现生成SQL语句出错：
SELECT COUNT(1) FROM tbl_user  WHERE  (name like '%'||@MethodConst0||'%')  

应该是 多了两个|| 字符。

**Comment by Yoodanet** [comment]
![EB2CF8AB-C2B2-4325-8601-354D3008536D](https://github.com/user-attachments/assets/005a1238-e1ea-4b2e-ab23-fc47d7487e51)

在上面的方法中，将条件转换成上面的语句。

**Comment by DotNetNext** [comment]
我处理一下吧，ODBC本来是不打算支持函数的，因为库太多了，遇到一个我支持一个吧

**Comment by DotNetNext** [comment]
升级到：SqlSugar.OdbcCore 5.1.4.168
升级到：SqlSugarCore 5.1.4.167-preview08   （勾预览）
已支持需要升级2个DLL

**Comment by Yoodanet** [comment]
已确认，可以正常使用了。非常感谢！！！
我在想InsertReturnEntityAsync 和 InsertReturnIdentityAsync 也能采用折中的办法支持一下就更好了，比其他类的框架更加完美和方便了。非常感谢！！！

**Comment by Yoodanet** [comment]
我调试InsertReturnIdentityAsync 时，发现生成的SQL语句如下：
INSERT INTO tbl_user (name,age)VALUES(@name,@age)112A689B-17A1-4A06-9D27-A39EAB8BC3D5
和提示错误消息相同：[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]接近 '112' 之處的語法不正確。
应该就是多了后面的“112A689B-17A1-4A06-9D27-A39EAB8BC3D5” 字符串。

**Comment by Yoodanet** [comment]
![image](https://github.com/user-attachments/assets/ecaddb62-a75e-4a49-afb5-9ea4645de2f7)
我看了一下，是在SQL模板生成SQL语句的地方生成的那个字符串。

**Comment by DotNetNext** [comment]
没用的，因为要查询自增就 要2行SQL ， select @@identity这种。 odbc只支持单SQL查询

**Comment by DotNetNext** [comment]
还有疑问发新的Issue
