### ISSUE TITLE
in 查询的转换会出错，不知道是不是我的写法有问题

### ISSUE THREAD

**Issue by JimmyTsai75** [DotNetNext/SqlSugar#1276]
我执行 db.Queryable<T>().TranLock(DbLockType.Error).Where(x=> allIds.Contains((x as IDatabaseModel).Id)).ToList();
目的是查询所有id在allIds里面的，我期待生成的Sql应该类似WHERE [Id] IN (2,3,31)，但是不知道我们，生成的sql多了一个(Result IN (2,3,31))，导致执行失败：

SELECT [Id],[TableName],[TbDescript],[PrimaryTB],[PrimaryKeyword],[StatisField],[PageSize],[DetailMaxRow],[Guid],[Deleted] FROM [A_Table_Info] WITH(UpdLock,RowLock,NoWait)  WHERE [Id] (Result IN (2,3,31))   AND ( [Deleted] = @Deleted1 )

**Comment by JimmyTsai75** [comment]
补充：我的数据库是mssql
我执行的时候是在一个泛型的类里面，执行代码db.Queryable<T>().TranLock(DbLockType.Error).Where(x=> allIds.Contains((x as IDatabaseModel).Id)).ToList();

如果我这个T改成了具体的类型，比如Order 生成的SQL里面就可以Result了，程序可以正常

**Comment by JimmyTsai75** [comment]
补充：我的数据库是mssql
我执行的时候是在一个泛型的类里面，执行代码db.Queryable(T).TranLock(DbLockType.Error).Where(x=> allIds.Contains((x as IDatabaseModel).Id)).ToList();

如果我这个T改成了具体的类型，比如Order 生成的SQL里面就可以Result了，程序可以正常

**Comment by JimmyTsai75** [comment]
补充：我的数据库是mssql
我执行的时候是在一个泛型的类里面，执行代码db.Queryable(T).TranLock(DbLockType.Error).Where(x=> allIds.Contains((x as IDatabaseModel).Id)).ToList();

如果我这个T改成了具体的类型，比如Order 生成的SQL里面就可以(没有Result）了，程序可以正常

**Comment by DotNetNext** [comment]
allIds.Contains(SqlFunc.MappingColumn<string>(nameof(IDatabaseModel.Id)))

改成这样试一下

**Comment by DotNetNext** [comment]
对了还有T要加 where:class,new() 先加上约束看看

**Comment by JimmyTsai75** [comment]
db.Queryable<T>().TranLock(DbLockType.Error).Where(x=>ids.Contains(SqlFunc.MappingColumn<int>(nameof(IDatabaseModel.Id)))).ToList();
改成这样是可以的。谢谢你。

**Comment by JimmyTsai75** [comment]
已经解决
