### ISSUE TITLE
[How to] usage IConditionalModel with Join Query?

### ISSUE THREAD

**Issue by mrreddevil2412** [DotNetNext/SqlSugar#1280]
`     /*** By dynamic***/

     //id=1
     var conModels = new List<IConditionalModel>();
     conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.Equal, FieldValue = "1" });//id=1
     var student = db.Queryable<Order>().Where(conModels).ToList();

     //Complex use case
     List<IConditionalModel> Order = new List<IConditionalModel>();
     conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.Equal, FieldValue = "1" });//id=1
     conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.Like, FieldValue = "1" });// id like '%1%'
     conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.IsNullOrEmpty });
     conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.In, FieldValue = "1,2,3" });
     conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.NotIn, FieldValue = "1,2,3" });
     conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.NoEqual, FieldValue = "1,2,3" });
     conModels.Add(new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.IsNot, FieldValue = null });// id is not null

     conModels.Add(new ConditionalCollections()
     {
         ConditionalList = new List<KeyValuePair<WhereType, SqlSugar.ConditionalModel>>()//  (id=1 or id=2 and id=1)
     {
         //new  KeyValuePair<WhereType, ConditionalModel>( WhereType.And ,new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.Equal, FieldValue = "1" }),
         new  KeyValuePair<WhereType, ConditionalModel> (WhereType.Or,new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.Equal, FieldValue = "2" }),
         new  KeyValuePair<WhereType, ConditionalModel> ( WhereType.And,new ConditionalModel() { FieldName = "id", ConditionalType = ConditionalType.Equal, FieldValue = "2" })
     }
     });
     var list6 = db.Queryable<Order>().Where(conModels).ToList();

     /*** Conditional builder ***/`
   SO how to use condition builder with JoinQuery?

**Comment by DotNetNext** [comment]
Whether the join table has an entity class 

entity join
```
 var conModels = new List<IConditionalModel>();
 conModels.Add(new ConditionalModel() { FieldName = "o.id", ConditionalType = ConditionalType.Equal, FieldValue = "1" }); 
var query5 = db.Queryable<Order>()
         .LeftJoin<Custom>((o,cus) => o.CustomId == cus.Id)//多个条件用&&
         .LeftJoin<OrderDetail> ((o,cus,oritem) => o.Id == oritem.OrderId)
         .Where(conModels )  
         .Select((o,cus,oritem) => new ViewOrder {Id=o.Id,CustomName = cus.Name })
         .ToList(); 
```

**Comment by DotNetNext** [comment]
No entity class
```cs
 var conModels = new List<IConditionalModel>();
 conModels.Add(new ConditionalModel() { FieldName = "o.id", ConditionalType = ConditionalType.Equal, FieldValue = "1" }); 
var list2 = db.Queryable<dynamic>("o").AS("order")
                        .AddJoinInfo("OrderDetail", "i", "o.id=i.OrderId")
                        .Where(conModels )
                        .Select("o.*").ToList();
```

**Comment by mrreddevil2412** [comment]
Thanks bro!
Is there a way to automatically distinguish it from the main table (or based on JoinType.Left or Right)
If that doesn't work, then maybe I'll have to write a function to handle the request

**Comment by DotNetNext** [comment]
I don't know what you mean

**Comment by mrreddevil2412** [comment]
`public class DynamicFilter
{
    public WhereType Logic { get; set; }

    public string? FieldName { get; set; }

    public ConditionalType ConditionalType { get; set; }

    public string? FieldValue { get; set; }

    public List<Filter>? Filters { get; set; }
}
public class PageInput
{
    private int _currentPage;
    private int _pageSize;

    /// <summary>
    /// trang hiện tại
    /// </summary>
    public virtual int Page
    {
        get => _currentPage < 1 ? 1 : _currentPage;
        set => _currentPage = value;
    }

    /// <summary>
    /// kích thước trang
    /// </summary>
    public virtual int PageSize
    {
        get
        {
            if (_pageSize < 1) _pageSize = 1;
            return _pageSize;
        }
        set => _pageSize = value;
    }

    public virtual DynamicFilter? DynamicFilter { get; set; } = null;
}

/// <summary>
/// Nhập thông tin phân trang
/// </summary>
/// <typeparam name="T">Lọc dữ liệu</typeparam>
public class PageInput<T> : PageInput
{
    /// <summary>
    /// condinal 
    /// </summary>
    public virtual T? Filter { get; set; }
}

//Api
  [HttpPost]
  [AuthAppHandle(ModuleCodeConfig.EmployeeInfo_Router, PermissionValue.View)]
  [CustomRoute(ApiVersions.v1, ModuleCodeConfig.EmployeeInfo_Paging)]
  public async Task<MessageModel<PageModel<EmployeesViewModel>>> GetDataPaging([FromBody] PageInput<EmployeeQuery_FilterModel> model)
      => Success(await _employee.DataPaging(model));
      // service
 List<IConditionalModel>? dynamicFilter = null;
 dynamicFilter = model.DynamicFilter?.ConvertToSqlSugarConditions();

 if (model.Filter?.orgId != null)
 {
     dynamicFilter ??= new List<IConditionalModel>();
     dynamicFilter.Add(new ConditionalModel { FieldName = "OrganizationId", ConditionalType = ConditionalType.Equal, FieldValue = model.Filter.orgId?.ToString() });
 }

 return await QueryMuchPage_Cache<Hr_Employee_Info_Entity, Hr_Employment_WorkPlaces_Entity, EmployeesViewModel>((o, x) => new object[]
             {
                     JoinType.Left , o.Id==x.EmployeeId
             },
                 (o, x) => new EmployeesViewModel
                 {
                     OrganizationName = SqlFunc.MappingColumn(default(string), " ([dbo].[Fn_Organiztion_GetName] (CONCAT([x].OrganizationId,',',[x].DepartmentId,',',[x].TeamId)))"),
                     Active = o.Active,
                     Avatar = o.AvatarPath,
                     FullName = o.FullName,
                     EmailOrganization = o.EmailPerson,
                     PhoneNumber = o.PhoneNumber,
                     EmployeeCode = o.EmployeeCode,
                     GenderName = o.Gender == 1 ? "Nam" : "Nữ",
                     DateOfBirth = o.DateOfBirth.Value.ToString("dd/MM/yyyy"),
                     EmployeeGuidId = o.Id.ToString(),
                     PositionName = SqlFunc.MappingColumn(default(string), " (dbo.[Fn_Category_GetName] ([x].RegencyId))"),
                     TypeContract = SqlFunc.MappingColumn(default(string), " (dbo.[Fn_Category_GetName] ([x].Contract_Type_Id))"),
                     StateCode = x.IsResignation,
                     UserName = o.UserName
                 }, (o, x) => o.IsDeleted == false,
                                  dynamicFilter,
                                  model.Page,
                                  model.PageSize,
                                   true,
                                  " [o].[Id] DESC",
                                  null
                                  );




    public static List<IConditionalModel>? ConvertToSqlSugarConditions(this DynamicFilter model)
    {
        if (model == null)
        {
            return null;
        }

        List<IConditionalModel> list = null;
        if (model.Filters != null)
        {
            if (list == null)
            {
                list = new List<IConditionalModel>();
            }

            IConditionalModel item = ProcessFilters(model.Filters, model.Logic);
            list.Add(item);
        }

        if (model.FieldName.IsNotEmptyOrNull() && model.FieldValue.IsNotEmptyOrNull())
        {
            if (list == null)
            {
                list = new List<IConditionalModel>();
            }

            list.Add(new ConditionalModel
            {
                FieldName = model.FieldName,
                ConditionalType = model.ConditionalType,
                FieldValue = model.FieldValue
            });
        }

        return list;
        static IConditionalModel ProcessFilters(List<Filter> filters, WhereType logic)
        {
            List<KeyValuePair<WhereType, IConditionalModel>> list2 = new List<KeyValuePair<WhereType, IConditionalModel>>();
            foreach (Filter filter in filters)
            {
                if (filter.Filters != null && filter.Filters.Count > 0)
                {
                    IConditionalModel value = ProcessFilters(filter.Filters, filter.Logic);
                    list2.Add(new KeyValuePair<WhereType, IConditionalModel>(WhereType.And, value));
                }
                else
                {
                    ConditionalType conditionalType = filter.ConditionalType;
                    list2.Add(new KeyValuePair<WhereType, IConditionalModel>(logic, new ConditionalModel
                    {
                        FieldName = filter.FieldName,
                        ConditionalType = conditionalType,
                        FieldValue = filter.FieldValue
                    }));
                }
            }

            return new ConditionalTree
            {
                ConditionalList = list2
            };
        }
    }

`
Above is the code to handle dynamic conditional filtering queries.
What I mean is how to automatically create filter conditions with table join, if I do it the way you did above I will have to add [o].  before fieldname.
So the ConvertToSqlSugarConditions function will have to be modified or no longer used

**Comment by DotNetNext** [comment]
.Select((o,cus,oritem) => new ViewOrder {Id=o.Id,CustomName = cus.Name })
        .MergeTable() //Merge into a table according to select
        .Where(conModels )//This equals a single table operation
         .ToList();

**Comment by DotNetNext** [comment]
MergeTable is followed by single-table operations

**Comment by mrreddevil2412** [comment]
Thanks you!
I'm try
