### ISSUE TITLE
求教：SqlSugar能否解决分类汇总式的查询

### ISSUE THREAD

**Issue by JimmyTsai75** [DotNetNext/SqlSugar#1281]
https://www.donet5.com/home/Doc?typeId=2315
SqlSugar的报表查询非常的赞！完美的解决了我的报表需求。
但是我需要更加麻烦的查询，就是报表查询的同时还能带出“详情”，比如某个销售报表Order，里面有Id，日期，销售人员，产品，金额等字段。
我需要生成一个每天的报表，这个用报表查询是OK的！
我的问题是：我还需要带出每天的销售数据，希望返回的数据类似这样的：
```JSON
[{
	"Date": "2024-01-01",
	"TotalAmount": 1782,
	"SaleData": [{
		"Id": 1,
		"Op": 30068,
		"Product": "Trv11002",
		"Qty": 1,
		"Amount": 1500
	}, {
		"Id": 1,
		"Product": "Tqx11002",
		"Qty": 1,
		"Op": 30067,
		"Amount": 282
	}]
}, {
	"Date": "2024-01-02",
	"TotalAmount": 0,
	"SaleData": []
}]

```
我不知道要如何去获取这个SaleData的数据，请求哪位达人给我个建议，谢谢。

**Comment by DotNetNext** [comment]
这个暂时没有方案，你这个行转列，还要有子对象 。

**Comment by JimmyTsai75** [comment]
好的，谢谢。我再想想别的替代办法
