### ISSUE TITLE
tdengine数据库转换sql不正确，Contains方法没有启动筛选作用

### ISSUE THREAD

**Issue by WsProgrammer** [DotNetNext/SqlSugar#1283]
![V 3VP2W54`06 QDUALL8(KI](https://github.com/user-attachments/assets/7437106d-34be-4cfa-b15e-ea6d5e71a35d)
![VZ7}$W`BF{5_Y(I0 V$04MV](https://github.com/user-attachments/assets/87724472-25fa-4fc4-89dc-3f594d8d40f7)
当想要字符串包含数据库字段的值，而不是数据库字段值包含某个字符串的时候，存在筛选失效问题

**Comment by DotNetNext** [comment]
tdengine反向like正确的SQL是什么样的

我试了几种都不行

 (@MethodConst0 like   `name`+'%'    )
 (@MethodConst0 like   concat(`name`,'%')   )

**Comment by WsProgrammer** [comment]
> tdengine反向like正确的SQL是什么样的
> 
> 我试了几种都不行
> 
> (@MethodConst0 like '%'+`name`+'%' ) (@MethodConst0 like concat( '%',`name`,'%') )

只是觉得这里生成的sql奇怪，具体能否实现上面的效果我没有验证

**Comment by DotNetNext** [comment]
目前tdengine不支持反射like 。如果你有研究出写法，在发issue，我暂时没有研究出写法。
