### ISSUE TITLE
包 "System.Drawing.Common" 4.7.0 具有已知的 严重 严重性漏洞

### ISSUE THREAD

**Issue by joesdu** [DotNetNext/SqlSugar#1287]
包 "System.Drawing.Common" 4.7.0 具有已知的 严重 严重性漏洞，https://github.com/advisories/GHSA-rxg9-xrhp-64gj
![image](https://github.com/user-attachments/assets/4115b5ec-68fc-4aa5-9dcc-0d929931c753)

**Comment by joesdu** [comment]
这个库的依赖根源来自于Microsoft.Data.SqlClient
![image](https://github.com/user-attachments/assets/23cfd1e2-df96-48bd-a535-33214a472511)

**Comment by DotNetNext** [comment]
截图你的nuget安装，这个DLL早就不引用了

**Comment by DotNetNext** [comment]
检查sqlsugar版本是不是最新  的是 167

**Comment by joesdu** [comment]
![新建 BMP 图像](https://github.com/user-attachments/assets/10ad1084-2a22-4638-8947-16505beef4ff)

**Comment by joesdu** [comment]
> 截图你的nuget安装，这个DLL早就不引用了

这个引用是由于间接引入了造成的.
![image](https://github.com/user-attachments/assets/f8072447-84d9-4eca-946a-2a9930b6dfd2)

**Comment by DotNetNext** [comment]
这个应该是你哪里冲突了，根本没有引用这个dll，Microsoft.Data.SqlClient  ,[2.1.7]  是8个月前有的补丁版本不会过时的

**Comment by DotNetNext** [comment]
还有疑问新建一个空DEMO，提供有警告的项目

**Comment by joesdu** [comment]
> 还有疑问新建一个空DEMO，提供有警告的项目 如果是冲突那你独立安装一下冲突的DLL

![image](https://github.com/user-attachments/assets/696da340-e239-4552-ba27-35da760f775e)

这个是新建的控制台项目,安装SqlSugarCoreNoDrive 5.1.4.167,他也安装了Microsoft.Data.SqlClient 2.1.7这个较低的版本并存在依赖项System.Data.Common 4.3.0
正在还原 C:\Users\Joe\source\repos\SqlSugar.Issuse1287.ConsoleApp\SqlSugar.Issuse1287.ConsoleApp\SqlSugar.Issuse1287.ConsoleApp.csproj 的包...
  CACHE https://api.nuget.org/v3/vulnerabilities/index.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.09.10.05.37.39/vulnerability.base.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.09.10.05.37.39/2024.09.10.23.37.40/vulnerability.update.json
正在安装 NuGet 程序包 SqlSugarCoreNoDrive 5.1.4.167。
将资产文件写入磁盘。路径: C:\Users\Joe\source\repos\SqlSugar.Issuse1287.ConsoleApp\SqlSugar.Issuse1287.ConsoleApp\obj\project.assets.json
已将“Microsoft.Data.SqlClient 2.1.7”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.Data.SqlClient.SNI.runtime 2.1.1”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.Identity.Client 4.21.1”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.IdentityModel.Abstractions 7.6.3”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.IdentityModel.JsonWebTokens 7.6.3”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.IdentityModel.Logging 7.6.3”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.IdentityModel.Protocols 6.8.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.IdentityModel.Protocols.OpenIdConnect 6.8.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.IdentityModel.Tokens 7.6.3”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.NETCore.Platforms 3.1.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.NETCore.Targets 1.1.3”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.Win32.Registry 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Microsoft.Win32.SystemEvents 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“Newtonsoft.Json 13.0.2”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“SqlSugarCoreNoDrive 5.1.4.167”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Collections 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Configuration.ConfigurationManager 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Data.Common 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Diagnostics.DiagnosticSource 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Drawing.Common 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Globalization 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.IdentityModel.Tokens.Jwt 7.6.3”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.IO 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Reflection 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Reflection.Emit.ILGeneration 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Reflection.Emit.Lightweight 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Reflection.Primitives 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Resources.ResourceManager 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Runtime 4.3.1”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Runtime.Caching 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Runtime.Extensions 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Security.AccessControl 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Security.Cryptography.ProtectedData 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Security.Permissions 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Security.Principal.Windows 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Text.Encoding 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Text.Encoding.CodePages 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Text.RegularExpressions 4.3.1”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Threading.Tasks 4.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“System.Windows.Extensions 4.7.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
已将“SystemCommon 8.3.0”成功安装到 SqlSugar.Issuse1287.ConsoleApp
执行 nuget 操作花费时间 167 毫秒
已用时间: 00:00:00.4378624
========== 已完成 ==========

已用时间: 00:00:00.0300780
========== 已完成 ==========

https://github.com/joesdu/SqlSugar.Issuse1287.ConsoleApp

**Comment by joesdu** [comment]
这个引用的传递是这个路径Microsoft.Data.SqlClient2.1.7 -> System.Runtime.Caching 4.7.0 -> System.Configuration.ConfigurationManager 4.7.0 -> System.Security.Permissions 4.7.0 -> System.Windows.Extensions 4.7.0 -> System.Drawing.Common 4.7.0,前面的所有4.7.0的包都没有被标记脆弱,但是System.Drawing.Common 4.7.0是被标记为脆弱的,而且一个SqlClient还间接引入了这个包本身也不太合理,我看了依赖关系,一直到Microsoft.Data.SqlClient5.2.0才彻底不再依赖System.Drawing.Common

**Comment by DotNetNext** [comment]
你先独立安装一下吧， 这个我想想怎么处理，官方Microsoft.Data.SqlClient2.1.7并没有过期只是依赖过期了，我想一下办法，如果我升级太高，对用户也有影响。

**Comment by DotNetNext** [comment]
![image](https://github.com/user-attachments/assets/2be7b2ad-3ccd-4045-abaa-d5d6a29ed7ab)
找到了这个dll过期了 ，我去微软提个BUG

**Comment by joesdu** [comment]
> ![image](https://private-user-images.githubusercontent.com/12455385/366329223-2be7b2ad-3ccd-4045-abaa-d5d6a29ed7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzczNzIsIm5iZiI6MTcyNjAzNzA3MiwicGF0aCI6Ii8xMjQ1NTM4NS8zNjYzMjkyMjMtMmJlN2IyYWQtM2NjZC00MDQ1LWFiYWEtZDVkNmEyOWVkN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA2NDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MDM3YjU1ZjcxMTBkMzVjODQzYmJhNTRlZWJmZWJjOTY4Mzc1ZGEzMzA5YmFmMGNhNTBhMDFjMmY0Mjg3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dKPhCHUx82fPflNxBqVU-4K49O09MyrhiW8yS68TBgQ) 找到了这个dll过期了 ，我去微软提个BUG

这个库我看我们公司这里间接引用的是7.6.3的版本,没有提示脆弱
![image](https://github.com/user-attachments/assets/fd223d6d-f2df-43df-97f2-6122cd966749)

**Comment by DotNetNext** [comment]
你升级最新看看

**Comment by DotNetNext** [comment]
就这个dll

**Comment by joesdu** [comment]
> 就这个dll

不行,在刚才那个示例的控制台程序中默认引用的也是7.6.3升级到8.0.2后还是会有System.Drawing.Common的高危漏洞提示.

**Comment by DotNetNext** [comment]
我在找一下更准的位置，Microsoft.Data.SqlClient这个DLL升级比较，字符串如果不false就会报错，新版本不友好。所以我一直用的补丁版本

**Comment by joesdu** [comment]
> 我在找一下更准的位置，Microsoft.Data.SqlClient这个DLL升级体验不好，字符串需要XXX=false, 不然多数环境就会报错，新版本不友好。所以我一直用的补丁版本

问题原因找到了,可以留着这个issues,有这个问题的人自己来升级这个库然后用到了的自己改就行.或者旧平台的用户继续使用旧版不升级了.

**Comment by DotNetNext** [comment]
> > 我在找一下更准的位置，Microsoft.Data.SqlClient这个DLL升级体验不好，字符串需要XXX=false, 不然多数环境就会报错，新版本不友好。所以我一直用的补丁版本
> 
> 问题原因找到了,可以留着这个issues,有这个问题的人自己来升级这个库然后用到了的自己改就行.或者旧平台的用户继续使用旧版不升级了.

NUGET这2天会更新的，我这边会想办法升级某个具体依赖

**Comment by DotNetNext** [comment]
5.1.4.169已发布，还有问题发新的issue
