### ISSUE TITLE
[Improvement] Reduce initial package dependency 

### ISSUE THREAD

**Issue by aloksharma1** [DotNetNext/SqlSugar#1291]
Hello,
when adding sqlsugarcore package it adds additional packages by default for:
 - oracle
 - Oscar
 - SqlClient
 - MySql
 - NpgSql
etc. while in practice users hardly use 1 or 2 types of databases in same project.
this is unnecessary weight to the application, instead you should be like ef core or other standard libraries where additional connectors come with their own dependencies that are configured on service building and startup.

**Comment by DotNetNext** [comment]
Nuget  ：  SqlSugarCoreNoDrive  
This will not load the default drivers.

**Comment by aloksharma1** [comment]
please add this info in readme

**Comment by flier268** [comment]
> Nuget ： SqlSugarCoreNoDrive This will not load the default drivers.

But, SqlSugarCoreNoDrive not support AOT

**Comment by aloksharma1** [comment]
ok in that case, my issue is still valid? is it possible to reduce package dependencies?

**Comment by DotNetNext** [comment]
> ok in that case, my issue is still valid. is it possible to reduce package dependencies without loosing AOT advantages?

AOT cannot use sqlsugarcorenodirve, it is currently not supported

**Comment by aloksharma1** [comment]
in that case can you give instructions on how we can compile package on local machine with 1 or 2 packages instead of all these for AOT, as i said in my original post we generally use one (or two types of db hardly) in most projects.

**Comment by DotNetNext** [comment]
[Only support mysql pgsql sqlerver sqlite ]
 SqlSugarCoreNoDrive.Aot
