### ISSUE TITLE
操作SqlServer数据库时AOPEvent事件不执行，由于行内部变量IsEnableLogEvent始终是false导致，如何处理？

### ISSUE THREAD

**Issue by 6314340** [DotNetNext/SqlSugar#1294]

**Comment by DotNetNext** [comment]
提供new sqlsugar和aop的代码，要按文档上面的地方写

**Comment by 6314340** [comment]
本地调试的截图
![A3D248D3-D5BD-4f37-920A-AA5DAB5E9AA2](https://github.com/user-attachments/assets/93334d7f-95ea-4340-9314-c47685972dcc)

注册sqlsugar的代码
`var configConnections = new List<ConnectionConfig>
{
	new ConnectionConfig()
	{
		ConfigId = "10",
		DbType = SqlSugar.DbType.SqlServer,
		ConnectionString = isFromApolloGetting ? configuration["JHBConnection"] :
							App.Configuration.GetConnectionString("JHBConnection"),
		IsAutoCloseConnection = true,
	},
	new ConnectionConfig()
	{
		ConfigId = "30",
		DbType = SqlSugar.DbType.SqlServer,
		ConnectionString = isFromApolloGetting ? configuration["JHBDataCenterConnection"]:
							App.Configuration.GetConnectionString("JHBDataCenterConnection"),
		IsAutoCloseConnection = true,
	}
};

services.AddSingleton<ISqlSugarClient>(s =>
{
    return new SqlSugarClient(conns, db =>
    {
        foreach (var conn in conns)
        {
            var profiler = new DefaultProfiler(_dataOptions, db, conn);
    
            db.GetConnection(conn.ConfigId).Aop.OnLogExecuted = profiler.OnLogExecuted;
            db.GetConnection(conn.ConfigId).Aop.OnError = profiler.OnError;
    
            db.GetConnectionScope(conn.ConfigId).Aop.OnLogExecuted = profiler.OnLogExecuted;
            db.GetConnectionScope(conn.ConfigId).Aop.OnError = profiler.OnError;
        }
    });
});`

执行SQL的代码
`var context = App.GetService<ISqlSugarClient>().AsTenant().GetConnectionScopeWithAttr<T>();        
var exportTask = await context.Queryable<T>().FirstAsync(d => d.Id == id));
`
