### ISSUE TITLE
使用Deleteable报错

### ISSUE THREAD

**Issue by domiuns** [DotNetNext/SqlSugar#1295]
- 报错：

await _sqlSugarClient.Deleteable<Entity>()
                    .Where(s => s.FirstName== name)
                    .WhereIF(!string.IsNullOrEmpty(lastName), s => s.LastName== lastName)
                    .ExecuteCommandAsync(cancellationToken);
                    
 - 不报错：
await _sqlSugarClient.Deleteable<Entity>()
                    .Where(s => s.FirstName== name)
                    .ExecuteCommandAsync(cancellationToken);
                    
                    
 报错内容：需要程序启动时配置StaticConfig.EnableAllWhereIF=true; 提示：该操作存在很大的风险如果没有条件很容易将整个表全部更新

**Comment by DotNetNext** [comment]
升级最新版本测试

**Comment by DotNetNext** [comment]
我看高版本处理过了，如果是你低版，需要StaticConfig.EnableAllWhereIF=true; 扔在程序启动时

**Comment by domiuns** [comment]
@DotNetNext 方便说一下在哪个版本修复的吗，因为我看你最新版本升级了SqlClient版本，我们项目不太方便升级。

**Comment by DotNetNext** [comment]
不升级就加上
StaticConfig.EnableAllWhereIF=true;   这样就没警告了
