### ISSUE TITLE
json2sql 如何使用casewhen函数

### ISSUE THREAD

**Issue by wodemingzijiaoke** [DotNetNext/SqlSugar#1296]
json中的select 我想使用
{
	"Table":["screenqueue","screenqueue"],
    "Select":[
		[{"SqlFunc_IIF":[
       "screenqueue._islocal = 0"
      ,"{string}:false","{string}:true"]},"SqlFunc_ToString"],
	]
}
第一个参数需要填入的是表达式，如何去写

**Comment by DotNetNext** [comment]
https://www.donet5.com/Ask/9/29890
