### ISSUE TITLE
Sqlite的SplitTable日期分表，时间为MinValue时的一些小问题

### ISSUE THREAD

**Issue by eijjxx** [DotNetNext/SqlSugar#1297]
按照时间分表且时间为MinValue时候
插入数据的时候，表名会按照DateTime.Now的时间创建，而插入的时间又是1900-1-1

我有一个需求是时间可能会变化时的Update，所以要查询旧数据的时间并创建表，如果旧表和新表不一致则需要delete+insert
这个时候会相当繁琐（没有找到根据ID查询表名的功能，SplitHelper.GetTableName在时间为DateTime.MinValue的时候也不对）

建议插入数据时如果时间为MinValue，可以将表名按照19000101创建（或者弄个特殊表名？）

**Comment by DotNetNext** [comment]
分表字段肯定必传

**Comment by DotNetNext** [comment]
这个暂时不改，影响比较大，传时间注意一下
