### ISSUE TITLE
 config DbMindate = null

### ISSUE THREAD

**Issue by mrreddevil2412** [DotNetNext/SqlSugar#1300]
Why I configure DbMinDate = null , but when adding a entity, the datetime column is still equal to 1900-01-01

![image](https://github.com/user-attachments/assets/ca1878af-0a9e-4271-af95-034541ca8edb)

**Comment by DotNetNext** [comment]
By default, it is designed to be compatible with various databases, such as SQL Server, where the minimum value cannot be less than 1900.

**Comment by mrreddevil2412** [comment]
> By default, it is designed to be compatible with various databases, such as SQL Server, where the minimum value cannot be less than 1900.
So is there any way to not automatically add the time? I want it to be null when inserting

**Comment by mrreddevil2412** [comment]
> By default, it is designed to be compatible with various databases, such as SQL Server, where the minimum value cannot be less than 1900.

So is there any way to not automatically add the time? I want it to be null when inserting

**Comment by DotNetNext** [comment]
use  DateTime?

**Comment by mrreddevil2412** [comment]
> use DateTime?

yes is dateTime?

**Comment by DotNetNext** [comment]
You can insert nulll without setting this property

public DateTime?  DateTime1 {get; set; }

**Comment by mrreddevil2412** [comment]
> You can insert nulll
> 
> public DateTime? DateTime1 {get; set; }

Thanks you!
