### ISSUE TITLE
模糊查询遭遇特殊符号时的问题

### ISSUE THREAD

**Issue by Naughtyhusky** [DotNetNext/SqlSugar#1303]
sqlsugar版本： SqlSugarCore 5.1.4.167
数据库： mysql

![image](https://github.com/user-attachments/assets/b63c73e7-4bb9-45f2-a8e6-7fcad762733c)
核心代码：
`WhereIF(!string.IsNullOrWhiteSpace(request.Applicant), (a, b, c) => b.Name.Contains(request.Applicant!))
`
生成的关键sql：
`WHERE  (`b`.`name` like concat('%',@MethodConst0,'%'))   {"@MethodConst0":"%%"}`

上述sql 等价于
` where( `b`.`name` like '%%%%' )`

由于 %%%% 允许名字包含任意数量的字符，这个模式实际上会匹配 name 字段中的任何值。换句话说，这个 LIKE 条件没有提供任何过滤，因此它相当于没有指定任何条件。

sqlsugar没有对输入的字符进行参数化或者转义？

我现在都有点怀疑这会不会有sql注入的风险了。

希望能尽早解决。

**Comment by DotNetNext** [comment]
这个是SQL的转LIKE符号 不存在SQL注入

**Comment by DotNetNext** [comment]
只要字符串包在参数化里面就是没有注入风险的

**Comment by DotNetNext** [comment]
var likeValue="\%\%";

在mysql如果你不想通配符号生效可以加上\

**Comment by Naughtyhusky** [comment]
> ```
> var likeValue="\%\%";
> ```
> 
> 在mysql如果你不想通配符号生效可以加上 因为LIKE的通配符号很多一般ORM不会去处理这些通配符号，用户自已处理需要的 ORM只要将字符串参数化就无注入风险

这里是接收页面属于的数据，你的意思是，程序代码里面对用户属于的文本进行检测，如果发现了有关特殊字符，就手动进行转义处理？

**Comment by DotNetNext** [comment]
加个replace替换就行了
