### ISSUE TITLE
关于人大金仓sys_config冲突问题

### ISSUE THREAD

**Issue by xisuo67** [DotNetNext/SqlSugar#1304]
今天拉着人大金仓的人一起看了关于sys_config，sys_user问题，我来两句，希望对下个版本有所帮助
首先目前存在的问题
![image](https://github.com/user-attachments/assets/a795ac5f-4723-4cea-88ae-b1743481d9ad)

![86d36289e2f522a8c89c11d6f3f0975](https://github.com/user-attachments/assets/6da37b2b-4482-47cf-8fd1-52b9faf56488)
我们在使用codefirst 初始化表结构的时候是直接查询这个表，如果存在就去修改这张表，而我们观察到通过控制台输出如下sql，
> select * from information schema.tables where pg catalog.UPPER(table name)=pg catalog.UPPER('Sys Config')
由于上述sql没有增加table_schema的判断，导致直接查询到系统表，由于系统存在这张表，导致初始化表结构的时候使用了alert 语句来修改表结构，所以一直会有冲突。我们是否可以增加一个判断，用于解决这个问题？如下图所示
<img width="773" alt="1731661303889" src="https://github.com/user-attachments/assets/51f468c9-6226-4a5b-8a6e-04b47f266916">

**Comment by DotNetNext** [comment]
什么模式，我记除sqlserver模式外都支持了

**Comment by DotNetNext** [comment]
提供金仓的 数据库模式

**Comment by xisuo67** [comment]
sqlserver

**Comment by DotNetNext** [comment]
SqlSugarCore 5.1.4.171-preview21
更新到 预览版本 已修复

**Comment by DotNetNext** [comment]
还有问题发新的issue ，先关闭

**Comment by xisuo67** [comment]
> 还有问题发新的issue ，先关闭

好的，我抽空验证一下

**Comment by xisuo67** [comment]
> SqlSugarCore 5.1.4.171-preview21 更新到 预览版本 已修复

这个版本似乎没了，上周看还有的
