### ISSUE TITLE
Connecting with HANA Studio

### ISSUE THREAD

**Issue by anandnathtiwari** [DotNetNext/SqlSugar#1305]
How connect with HANA Database with Sap.Data.Hana.v4.5 ? 
Is it Possible ?

**Comment by DotNetNext** [comment]
Not supported at the moment.

**Comment by anandnathtiwari** [comment]
Is any one help me to implement Sap.Data.Hana. I will ready for paid service.

**Comment by DotNetNext** [comment]
Payment is acceptable, but I don't have an overseas account. Can you use WeChat Pay from China?

**Comment by anandnathtiwari** [comment]
other payment gateway ?
I am from India.
are you using paypal or google pay

**Comment by DotNetNext** [comment]
I apologize, I don't have any other payment options.

**Comment by DotNetNext** [comment]
![image](https://github.com/user-attachments/assets/268bd8e3-4cb5-473b-b0cf-81e737defda0)
You can refer to my extended other libraries, and then merge them for me.

**Comment by anandnathtiwari** [comment]
If you will  help me then I will share my code with you
Please share email id to send source code.
I am not aware about github merge

**Comment by DotNetNext** [comment]
610262374@qq.com      email     
I'll try to cooperate with you fully  Hana Connector

**Comment by anandnathtiwari** [comment]
Please check you mail.

Thanks

**Comment by DotNetNext** [comment]
> Please check you mail.
> 
> Thanks

I received it, but I am experiencing network issues and cannot access GitHub at the moment. I expect to be able to push it to GITHUB next Monday.

**Comment by anandnathtiwari** [comment]
Ok. 
Thanks

**Comment by DotNetNext** [comment]
It has already been synchronized

**Comment by anandnathtiwari** [comment]
How I use hana.connector in [zuohuaijun](https://github.com/zuohuaijun)

[Admin.NET](https://github.com/zuohuaijun/Admin.NET)

**Comment by DotNetNext** [comment]
SqlSugar.HanaConnector must support CodeFirst and sqlsugar add, delete and modify

**Comment by DotNetNext** [comment]
If it is supported, there is no problem just change his json file

**Comment by anandnathtiwari** [comment]
Thanks
