### ISSUE TITLE
[feature request] SqlSugar  dynamic 结果 考虑自己建立一个 动态字典，不要用 ExpandoObject

### ISSUE THREAD

**Issue by John0King** [DotNetNext/SqlSugar#1307]
## backgorund  / 背景

数据库里面字段名称有的数据库区分大小写， 有的不区分大小写， 对于区分大小的的数据库比如 Oracle/ Postgresql, 等他们默认的大小写名称不同， 对于编程这边很难对dynamic 字段的大小写进行定下来， 而 dataTable 可以同时支持  区分大小写和不区分大小写， 基本规则是， dataTable 优先匹配区分大小写字段名， 找不到再以 `StringComparer.OrdinalIgnoreCase` 来匹配第一个.

```sql
select aBc from someTable

```
以上sql, 在 ORALCE  里面相当于   `select "ABC" from "SOMETABLE"`  而在 posgresql 里面相当于 `select "abc" from "sometable"`

## 建议

采用自己独立的 `IDynamicMetaObjectProvider`   跟 DataTable 一样， 优先以 区分大小写的匹配， 再以不区分大小写的方式匹配， 这样以下语句都可以得到值

```c#
var a= db.Ado.SqlQuerySingle<dynamic>(“”“
select 1 as "Abc" , 2 as "abc" , 3 as "dEf" from dual
”“”);

a.Abc // 1
a.abc // 2
a.def // 3

```

**Comment by DotNetNext** [comment]
你是用的实体 查询还是用的 db.ado 查询描述清楚问题 取一个具体用例

**Comment by DotNetNext** [comment]
你的例子怎么有四个双影号

**Comment by John0King** [comment]
🤣  c# 12的原始字面值，打成中文括号了

**Comment by DotNetNext** [comment]
ExpandoObject  可以转成字典的

**Comment by DotNetNext** [comment]
如果你只是写SQL你加 as "xx" 自个加关键词转译就行了

**Comment by John0King** [comment]
但是一般谁会写  `select  t.ABC as "ABC" `  这种😅  ,  而且一般用 SqlSugar 都是有不同数据库需求;   
动态字典， 可以通过继承 `DynamicObject` 类来简化实现

**Comment by DotNetNext** [comment]
InstanceFactory.GetSqlBuilderWithContext(db)
        .GetTranslationColumnName("id");

**Comment by DotNetNext** [comment]
有这个方法可以获取 ORM的字符格式化

**Comment by John0King** [comment]
那个实现自己的动态字典有什么难处么？ 
还是担心跟文档上 ExpandoObject 的兼容性问题？ 
（兼容性问题可以试试能不能用 隐式/显示转换解决）

**Comment by DotNetNext** [comment]
不是很清楚你要什么东西 ，下面的这样不行吗

db.Ado.SqlQuerySingle<自定义类型>

**Comment by John0King** [comment]
周末看看我有时间么，我想提交个pr

**Comment by DotNetNext** [comment]
好的

**Comment by DotNetNext** [comment]
直接PULL先关闭
