### ISSUE TITLE
分表（SplitTable）Insert or update: Storageable  How to use ToStorage()

### ISSUE THREAD

**Issue by 2009011133** [DotNetNext/SqlSugar#1308]
预期：
var x=db.Storageable(data).SplitTable().WhereColumns(w=>w.md5).ToStorage();
x.AsInsertable.ExecuteCommand();//不存在插入
x.AsUpdateable.ExecuteCommand();//存在更新

**Comment by DotNetNext** [comment]
var x=db.Storageable(data).SplitTable().WhereColumns(w=>w.md5).ExecuteCommand();

高版本支持这种写法，不能分开
