### ISSUE TITLE
sqlSugarCore版本升级到哪一版本，更新主键操作失效了呢？

### ISSUE THREAD

**Issue by payne713** [DotNetNext/SqlSugar#1313]
测试结果：
5.0.0.10版本：  更新主键成功
5.1.4.170版本：更新主键失败

**Comment by DotNetNext** [comment]
主键不能更新

**Comment by DotNetNext** [comment]
![image](https://github.com/user-attachments/assets/242b123c-8adb-4e59-8b70-285ce7717739)

**Comment by payne713** [comment]
我用5.0.0.10版本可以更新成功的

**Comment by DotNetNext** [comment]
那个是比较老的了，考虑安全原因主键不让他更新

**Comment by DotNetNext** [comment]
默认主键只能是条件
