### ISSUE TITLE
Pull代码给我 ，请Pull SqlSugar版本

### ISSUE THREAD

**Issue by DotNetNext** [DotNetNext/SqlSugar#849]
因为我是以SqlSugar为标准 ，然后复制到Core版本的

**Comment by skh1997** [comment]
![image](https://user-images.githubusercontent.com/46045819/190570186-339a33d3-1288-43ca-b2f5-3e43c6901fd7.png)
SqlFunc语法错误，sqlsugar版本5.1.3.1
